# Generated by Django 6.0 on 2026-01-03 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('closed', 'مغلق'), ('maintenance', 'صيانة')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.door')),
                ('shift_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.shiftplan')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.door')),
            ],
        ),
    ]
