# Generated by Django 6.0 on 2026-01-03 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_door_options_alter_zone_options_zone_notes_and_more'),
        ('ops', '0001_initial'),
        ('scheduling', '0002_alter_shiftassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doorstatus',
            options={'ordering': ['-timestamp'], 'verbose_name': 'حالة باب', 'verbose_name_plural': 'حالات الأبواب'},
        ),
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'طلب صيانة', 'verbose_name_plural': 'طلبات الصيانة'},
        ),
        migrations.AddField(
            model_name='doorstatus',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة'),
        ),
        migrations.AlterField(
            model_name='doorstatus',
            name='door',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.door', verbose_name='الباب'),
        ),
        migrations.AlterField(
            model_name='doorstatus',
            name='shift_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.shiftplan', verbose_name='الوردية'),
        ),
        migrations.AlterField(
            model_name='doorstatus',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوح'), ('closed', 'مغلق'), ('maintenance', 'صيانة')], max_length=20, verbose_name='حالة الباب'),
        ),
        migrations.AlterField(
            model_name='doorstatus',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت تسجيل الحالة'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='description',
            field=models.TextField(verbose_name='وصف العطل'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='door',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.door', verbose_name='الباب'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='resolved',
            field=models.BooleanField(default=False, verbose_name='تمت المعالجة'),
        ),
    ]
