# Generated by Django 6.0 on 2026-01-07 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_door_options_alter_zone_options_zone_notes_and_more'),
        ('ops', '0002_alter_doorstatus_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='door',
        ),
        migrations.CreateModel(
            name='DoorShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='بداية الوردية')),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_shifts', to='locations.door', verbose_name='الباب')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_doors', to=settings.AUTH_USER_MODEL, verbose_name='المشرف المناوب')),
            ],
            options={
                'verbose_name': 'وردية باب',
                'verbose_name_plural': 'ورديات الأبواب',
                'ordering': ['door'],
            },
        ),
        migrations.DeleteModel(
            name='DoorStatus',
        ),
        migrations.DeleteModel(
            name='MaintenanceRequest',
        ),
    ]
