# Generated by Django 6.0 on 2026-01-07 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_remove_maintenancerequest_door_doorshift_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doorshift',
            options={'ordering': ['door_number'], 'verbose_name': 'حالة باب', 'verbose_name_plural': 'حالات الأبواب'},
        ),
        migrations.RemoveField(
            model_name='doorshift',
            name='door',
        ),
        migrations.RemoveField(
            model_name='doorshift',
            name='started_at',
        ),
        migrations.AddField(
            model_name='doorshift',
            name='door_number',
            field=models.PositiveIntegerField(default=0, verbose_name='رقم الباب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doorshift',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='doorshift',
            name='state',
            field=models.CharField(choices=[('open', 'مفتوح'), ('closed', 'مغلق'), ('maint', 'صيانة')], default='open', max_length=10, verbose_name='حالة الباب'),
        ),
        migrations.AddField(
            model_name='doorshift',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='doorshift',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='وردية نشطة'),
        ),
        migrations.AlterField(
            model_name='doorshift',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='door_shifts', to=settings.AUTH_USER_MODEL, verbose_name='مشرف الباب المناوب'),
        ),
    ]
