# Generated by Django 6.0 on 2026-01-07 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0004_alter_doorshift_options_remove_doorshift_door_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorshift',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='وردية نشطة'),
        ),
        migrations.AlterField(
            model_name='doorshift',
            name='state',
            field=models.CharField(choices=[('open', 'مفتوح'), ('closed', 'مغلق'), ('maintenance', 'تحت صيانة')], db_index=True, default='open', max_length=20, verbose_name='حالة الباب'),
        ),
        migrations.AddIndex(
            model_name='doorshift',
            index=models.Index(fields=['door_number'], name='ops_doorshi_door_nu_7f81bc_idx'),
        ),
        migrations.AddIndex(
            model_name='doorshift',
            index=models.Index(fields=['state'], name='ops_doorshi_state_dc60f6_idx'),
        ),
        migrations.AddIndex(
            model_name='doorshift',
            index=models.Index(fields=['is_active'], name='ops_doorshi_is_acti_4cc5f1_idx'),
        ),
    ]
