# Generated by Django 6.0 on 2026-01-11 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0005_alter_doorshift_is_active_alter_doorshift_state_and_more'),
        ('scheduling', '0003_alter_shiftplan_options_alter_shifttype_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doorshift',
            name='shift_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='door_shifts', to='scheduling.shiftplan', verbose_name='الوردية'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doorshift',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='نشطة'),
        ),
        migrations.AlterUniqueTogether(
            name='doorshift',
            unique_together={('door_number', 'shift_plan')},
        ),
        migrations.AddIndex(
            model_name='doorshift',
            index=models.Index(fields=['shift_plan'], name='ops_doorshi_shift_p_9eb1dc_idx'),
        ),
    ]
