# Generated by Django 6.0 on 2026-01-11 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0006_doorshift_shift_plan_alter_doorshift_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='وصف المشكلة')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'قيد التنفيذ'), ('done', 'منجز')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'طلب صيانة',
                'verbose_name_plural': 'طلبات الصيانة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='doorshift',
            name='ops_doorshi_door_nu_7f81bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='doorshift',
            name='ops_doorshi_state_dc60f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='doorshift',
            name='ops_doorshi_is_acti_4cc5f1_idx',
        ),
        migrations.RemoveIndex(
            model_name='doorshift',
            name='ops_doorshi_shift_p_9eb1dc_idx',
        ),
        migrations.AlterField(
            model_name='doorshift',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='doorshift',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doorshift',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_doors', to=settings.AUTH_USER_MODEL, verbose_name='مشرف الباب المناوب'),
        ),
        migrations.AlterField(
            model_name='doorshift',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='door_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='ops.doorshift', verbose_name='الباب'),
        ),
    ]
