# Generated by Django 6.0 on 2026-01-12 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0007_maintenancerequest_and_more'),
        ('scheduling', '0004_alter_shiftplan_options_shiftassignment_assigned_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doorshift',
            options={'ordering': ['door_number'], 'permissions': [('can_update_door_state', 'يمكن تحديث حالة الباب'), ('can_assign_door_supervisor', 'يمكن تعيين مشرف الباب')], 'verbose_name': 'حالة باب', 'verbose_name_plural': 'حالات الأبواب'},
        ),
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'ordering': ['-created_at'], 'permissions': [('can_create_maintenance', 'يمكن إنشاء طلب صيانة'), ('can_update_maintenance_status', 'يمكن تغيير حالة طلب الصيانة')], 'verbose_name': 'طلب صيانة', 'verbose_name_plural': 'طلبات الصيانة'},
        ),
        migrations.AlterField(
            model_name='doorshift',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='doorshift',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='doorshift',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'قيد التنفيذ'), ('done', 'منجز')], db_index=True, default='open', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.AddIndex(
            model_name='doorshift',
            index=models.Index(fields=['door_number'], name='ops_doorshi_door_nu_7f81bc_idx'),
        ),
        migrations.AddIndex(
            model_name='doorshift',
            index=models.Index(fields=['state'], name='ops_doorshi_state_dc60f6_idx'),
        ),
        migrations.AddIndex(
            model_name='doorshift',
            index=models.Index(fields=['shift_plan'], name='ops_doorshi_shift_p_9eb1dc_idx'),
        ),
        migrations.AddIndex(
            model_name='doorshift',
            index=models.Index(fields=['is_active'], name='ops_doorshi_is_acti_4cc5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['status'], name='ops_mainten_status_bc6388_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['created_at'], name='ops_mainten_created_38e75f_idx'),
        ),
    ]
