# Generated by Django 6.0 on 2026-06-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0008_alter_doorshift_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorshift',
            name='state',
            field=models.CharField(choices=[('open', 'مفتوح'), ('closed', 'مغلق'), ('maintenance', 'تحت صيانة'), ('secured', 'مؤمّن')], db_index=True, default='open', max_length=20, verbose_name='حالة الباب'),
        ),
    ]
