# Generated by Django 6.0 on 2026-06-22 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0009_alter_doorshift_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'ordering': ['-created_at'], 'permissions': [('can_create_maintenance', 'يمكن إنشاء طلب صيانة'), ('can_approve_maintenance', 'يمكن اعتماد طلب صيانة'), ('can_assign_maintenance', 'يمكن تحويل طلب الصيانة للفريق الفني'), ('can_update_maintenance_status', 'يمكن تغيير حالة طلب الصيانة'), ('can_close_maintenance', 'يمكن إغلاق طلب الصيانة')], 'verbose_name': 'طلب صيانة', 'verbose_name_plural': 'طلبات الصيانة'},
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحويل للفريق الفني'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='closing_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات الإغلاق'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='fixed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإصلاح'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/', verbose_name='صورة المشكلة'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجلة')], db_index=True, default='medium', max_length=20, verbose_name='درجة الخطورة'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='request_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True, verbose_name='رقم الطلب'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ بدء التنفيذ'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance_requests', to=settings.AUTH_USER_MODEL, verbose_name='الفني المكلف'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('approved', 'معتمد'), ('assigned', 'محول للفريق الفني'), ('in_progress', 'قيد التنفيذ'), ('fixed', 'تم الإصلاح'), ('closed', 'مغلق'), ('open', 'مفتوح'), ('done', 'منجز')], db_index=True, default='new', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['request_number'], name='ops_mainten_request_27608d_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['priority'], name='ops_mainten_priorit_96dec7_idx'),
        ),
    ]
