# Generated by Django 6.0 on 2026-06-23 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0010_alter_maintenancerequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='technician_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='اسم الفني المنفذ'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المنفذ للطلب'),
        ),
    ]
