# Generated by Django 6.0 on 2026-06-24 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0011_maintenancerequest_technician_name_and_more'),
        ('scheduling', '0005_alter_shiftassignment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_number', models.CharField(blank=True, db_index=True, max_length=50, unique=True, verbose_name='رقم البلاغ')),
                ('incident_type', models.CharField(choices=[('door_fault', 'عطل باب'), ('crowding', 'ازدحام'), ('operational_violation', 'مخالفة تشغيلية'), ('security', 'بلاغ أمني'), ('cleaning', 'بلاغ نظافة'), ('technical', 'بلاغ تقني'), ('maintenance', 'بلاغ صيانة'), ('general', 'بلاغ عام')], db_index=True, default='general', max_length=40, verbose_name='نوع البلاغ')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('critical', 'حرجة')], db_index=True, default='medium', max_length=20, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('in_progress', 'قيد المعالجة'), ('forwarded', 'تم التوجيه'), ('resolved', 'تم الحل'), ('closed', 'مغلق')], db_index=True, default='new', max_length=20, verbose_name='حالة البلاغ')),
                ('description', models.TextField(verbose_name='وصف البلاغ')),
                ('reported_by_name', models.CharField(blank=True, max_length=150, verbose_name='اسم المبلغ')),
                ('assigned_to_name', models.CharField(blank=True, max_length=150, verbose_name='محول إلى')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('closing_notes', models.TextField(blank=True, verbose_name='ملاحظات الإغلاق')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_incidents', to=settings.AUTH_USER_MODEL, verbose_name='أُغلق بواسطة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incidents', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('door_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='ops.doorshift', verbose_name='الباب')),
                ('shift_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='scheduling.shiftplan', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'بلاغ تشغيلي',
                'verbose_name_plural': 'البلاغات التشغيلية',
                'ordering': ['-created_at'],
                'permissions': [('can_create_incident', 'يمكن إنشاء بلاغ تشغيلي'), ('can_update_incident_status', 'يمكن تحديث حالة البلاغ'), ('can_close_incident', 'يمكن إغلاق البلاغ')],
                'indexes': [models.Index(fields=['incident_number'], name='ops_inciden_inciden_ffeb1b_idx'), models.Index(fields=['incident_type'], name='ops_inciden_inciden_c04a2a_idx'), models.Index(fields=['priority'], name='ops_inciden_priorit_8b1dee_idx'), models.Index(fields=['status'], name='ops_inciden_status_5bbcde_idx'), models.Index(fields=['created_at'], name='ops_inciden_created_61dfec_idx')],
            },
        ),
    ]
