# Generated by Django 6.0 on 2026-07-17 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0012_incident'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'ordering': ['-created_at'], 'permissions': [('can_create_maintenance', 'يمكن إنشاء طلب صيانة'), ('can_approve_maintenance', 'يمكن اعتماد طلب صيانة'), ('can_assign_maintenance', 'يمكن تحويل الطلب للفريق الفني'), ('can_update_maintenance_status', 'يمكن تحديث حالة الطلب'), ('can_close_maintenance', 'يمكن إغلاق طلب الصيانة')], 'verbose_name': 'طلب صيانة', 'verbose_name_plural': 'طلبات الصيانة'},
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='after_image',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/after/', verbose_name='صورة بعد الإصلاح'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_maintenance_requests', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by_maintenance_requests', to=settings.AUTH_USER_MODEL, verbose_name='حوّل بواسطة'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='before_image',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/before/', verbose_name='صورة قبل الإصلاح'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=120, verbose_name='المدة المتوقعة بالدقائق'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تقييم الإصلاح'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='technician_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم جوال الفني'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='assigned_to_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='محوّل إلى'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('approved', 'معتمد'), ('assigned', 'محول للفريق الفني'), ('in_progress', 'قيد التنفيذ'), ('fixed', 'تم الإصلاح'), ('open', 'مفتوح'), ('done', 'منجز'), ('closed', 'مغلق')], db_index=True, default='new', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['door_shift'], name='ops_mainten_door_sh_40842f_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['technician'], name='ops_mainten_technic_b319ea_idx'),
        ),
    ]
