# Generated by Django 6.0 on 2026-07-29 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0013_alter_maintenancerequest_options_and_more'),
        ('scheduling', '0008_season_seasonalshifttemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-created_at'], 'verbose_name': 'بلاغ تشغيلي', 'verbose_name_plural': 'البلاغات التشغيلية'},
        ),
        migrations.AlterField(
            model_name='incident',
            name='assigned_to_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='incident',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='closing_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='incident',
            name='door_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='ops.doorshift'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('door_fault', 'عطل باب'), ('crowding', 'ازدحام'), ('operational_violation', 'مخالفة تشغيلية'), ('security', 'بلاغ أمني'), ('cleaning', 'بلاغ نظافة'), ('technical', 'بلاغ تقني'), ('maintenance', 'بلاغ صيانة'), ('general', 'بلاغ عام')], default='general', max_length=40),
        ),
        migrations.AlterField(
            model_name='incident',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('critical', 'حرجة')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='reported_by_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='incident',
            name='shift_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='scheduling.shiftplan'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('in_progress', 'قيد المعالجة'), ('forwarded', 'تم التوجيه'), ('resolved', 'تم الحل'), ('closed', 'مغلق')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
