# Generated by Django 6.0 on 2026-07-31 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_door_options_and_more'),
        ('ops', '0014_alter_incident_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorCurrentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('open', 'مفتوح'), ('closed', 'مغلق'), ('maintenance', 'تحت صيانة'), ('secured', 'مؤمّن')], db_index=True, default='open', max_length=20, verbose_name='الحالة الحالية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات الحالة')),
                ('update_source', models.CharField(choices=[('operations', 'العمليات'), ('maintenance', 'الصيانة'), ('system', 'النظام')], db_index=True, default='operations', max_length=20, verbose_name='مصدر التحديث')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخر تحديث')),
                ('current_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_state_snapshots', to='ops.doorshift', verbose_name='سجل الباب في الوردية الحالية')),
                ('door', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_state', to='locations.door', verbose_name='الباب')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_door_current_states', to=settings.AUTH_USER_MODEL, verbose_name='آخر تحديث بواسطة')),
            ],
            options={
                'verbose_name': 'الحالة الحالية للباب',
                'verbose_name_plural': 'الحالات الحالية للأبواب',
                'ordering': ['door__door_number'],
                'permissions': [('can_view_all_current_door_states', 'يمكن عرض جميع الحالات الحالية للأبواب')],
                'indexes': [models.Index(fields=['state'], name='door_current_state_idx'), models.Index(fields=['update_source'], name='door_current_source_idx'), models.Index(fields=['updated_at'], name='door_current_updated_idx')],
            },
        ),
    ]
