# Generated by Django 6.0 on 2026-08-07 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0007_alter_doorassignment_options_and_more'),
        ('ops', '0015_doorcurrentstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorshift',
            name='section',
            field=models.CharField(blank=True, choices=[('male', 'رجالي'), ('female', 'نسائي')], db_index=True, default='', max_length=10, verbose_name='القسم التشغيلي'),
        ),
        migrations.AddField(
            model_name='incident',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='distribution.doorassignment', verbose_name='التسكين المرتبط'),
        ),
        migrations.AddField(
            model_name='incident',
            name='section',
            field=models.CharField(blank=True, choices=[('male', 'رجالي'), ('female', 'نسائي')], db_index=True, default='', max_length=10, verbose_name='القسم التشغيلي'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='distribution.doorassignment', verbose_name='التسكين المرتبط'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='section',
            field=models.CharField(blank=True, choices=[('male', 'رجالي'), ('female', 'نسائي')], db_index=True, default='', max_length=10, verbose_name='القسم التشغيلي'),
        ),
    ]
