# Generated by Django 6.0 on 2026-08-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0017_backfill_legacy_operational_sections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doorshift',
            options={'ordering': ['sort_order', 'door_number'], 'permissions': [('can_update_door_state', 'يمكن تحديث حالة الباب'), ('can_assign_door_supervisor', 'يمكن تعيين مشرف الباب')], 'verbose_name': 'حالة باب', 'verbose_name_plural': 'حالات الأبواب'},
        ),
        migrations.AddField(
            model_name='doorshift',
            name='sort_order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, editable=False, verbose_name='ترتيب الباب الرسمي'),
        ),
        migrations.AlterField(
            model_name='doorshift',
            name='door_number',
            field=models.CharField(db_index=True, max_length=10, verbose_name='رقم الباب'),
        ),
    ]
