# Generated by Django 6.0.8 on 2026-08-24 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0021_maintenancerequest_planned_window'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='escalated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_operational_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='escalation_level',
            field=models.CharField(choices=[('none', 'غير مصعّد'), ('department_head', 'رئيس قسم الأبواب'), ('general_manager', 'المدير العام')], db_index=True, default='none', max_length=30, verbose_name='مستوى التصعيد'),
        ),
        migrations.AddField(
            model_name='incident',
            name='escalation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='source_incident',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_request', to='ops.incident', verbose_name='البلاغ التشغيلي المصدر'),
        ),
        migrations.CreateModel(
            name='IncidentRoutingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'إنشاء البلاغ'), ('assigned', 'إسناد البلاغ'), ('processing_started', 'بدء المعالجة'), ('escalated', 'تصعيد البلاغ'), ('converted_to_maintenance', 'تحويل إلى الصيانة'), ('maintenance_approved', 'اعتماد الصيانة'), ('maintenance_started', 'بدء الصيانة'), ('maintenance_completed', 'اكتمال الصيانة'), ('closed', 'إغلاق البلاغ')], db_index=True, max_length=40)),
                ('target_level', models.CharField(blank=True, choices=[('none', 'غير مصعّد'), ('department_head', 'رئيس قسم الأبواب'), ('general_manager', 'المدير العام')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_routing_events', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_events', to='ops.incident')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_incident_routing_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
