# Generated by Django 6.0 on 2026-08-26 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0023_dooroperationalprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentSupervisoryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('request_update', 'طلب تحديث'), ('supervisory_note', 'ملاحظة إشرافية'), ('administrative_note', 'ملاحظة إدارية'), ('supervisory_directive', 'توجيه إشرافي'), ('executive_directive', 'توجيه تنفيذي'), ('return_to_followup', 'إعادة للمتابعة'), ('escalate_to_general_manager', 'تصعيد للمدير العام'), ('administrative_alert', 'تنبيه إداري'), ('supervisory_resolved', 'معالجة إشرافية'), ('response', 'استجابة')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('acknowledged', 'تم الاطلاع'), ('completed', 'مكتمل'), ('resolved', 'معالج إشرافيًا')], db_index=True, default='open', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acting_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delegated_incident_supervisory_actions', to=settings.AUTH_USER_MODEL)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incident_supervisory_actions', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisory_actions', to='ops.incident')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='ops.incidentsupervisoryaction')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_incident_supervisory_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['incident', 'status', 'created_at'], name='ops_inciden_inciden_6c911e_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeadershipDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('male', 'رجالي'), ('female', 'نسائي')], db_index=True, max_length=10)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leadership_delegations_created', to=settings.AUTH_USER_MODEL)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leadership_delegations_received', to=settings.AUTH_USER_MODEL)),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leadership_delegations_given', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leadership_delegations_revoked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at', '-pk'],
                'indexes': [models.Index(fields=['section', 'starts_at', 'ends_at'], name='ops_leaders_section_5be601_idx')],
            },
        ),
    ]
