# Generated by Django 6.0 on 2026-08-26 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0024_incidentsupervisoryaction_leadershipdelegation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentsupervisoryaction',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentsupervisoryaction',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acknowledged_incident_supervisory_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentsupervisoryaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentsupervisoryaction',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_incident_supervisory_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentsupervisoryaction',
            name='completion_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='incidentsupervisoryaction',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوح'), ('answered', 'تم الرد'), ('acknowledged', 'تم الاطلاع'), ('completed', 'مكتمل'), ('resolved', 'معالج إشرافيًا')], db_index=True, default='open', max_length=20),
        ),
    ]
