# Generated by Django 6.0 on 2026-06-22 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ops', '0009_alter_doorshift_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_state', models.CharField(max_length=20)),
                ('new_state', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('approved_by', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ops.doorshift')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
