# Generated by Django 6.0 on 2026-06-22 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('ops', '0009_alter_doorshift_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doorauditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'سجل تغيير باب', 'verbose_name_plural': 'سجلات تغييرات الأبواب'},
        ),
        migrations.AlterField(
            model_name='doorauditlog',
            name='approved_by',
            field=models.CharField(max_length=200, verbose_name='المسؤول المعتمد'),
        ),
        migrations.AlterField(
            model_name='doorauditlog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='door_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='نفذ بواسطة'),
        ),
        migrations.AlterField(
            model_name='doorauditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العملية'),
        ),
        migrations.AlterField(
            model_name='doorauditlog',
            name='door',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ops.doorshift', verbose_name='الباب'),
        ),
        migrations.AlterField(
            model_name='doorauditlog',
            name='new_state',
            field=models.CharField(max_length=20, verbose_name='الحالة الجديدة'),
        ),
        migrations.AlterField(
            model_name='doorauditlog',
            name='old_state',
            field=models.CharField(max_length=20, verbose_name='الحالة السابقة'),
        ),
        migrations.AlterField(
            model_name='doorauditlog',
            name='reason',
            field=models.TextField(verbose_name='سبب التغيير'),
        ),
        migrations.AddIndex(
            model_name='doorauditlog',
            index=models.Index(fields=['created_at'], name='dashboard_d_created_03c8eb_idx'),
        ),
        migrations.AddIndex(
            model_name='doorauditlog',
            index=models.Index(fields=['old_state'], name='dashboard_d_old_sta_2fb300_idx'),
        ),
        migrations.AddIndex(
            model_name='doorauditlog',
            index=models.Index(fields=['new_state'], name='dashboard_d_new_sta_91a6fd_idx'),
        ),
    ]
