# Generated by Django 6.0 on 2026-07-05 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_doorauditlog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, max_length=100, verbose_name='القسم')),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('export', 'تصدير'), ('approve', 'اعتماد'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('other', 'أخرى')], db_index=True, max_length=20, verbose_name='نوع العملية')),
                ('description', models.TextField(verbose_name='وصف العملية')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='التاريخ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل نشاط',
                'verbose_name_plural': 'سجل نشاط النظام',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module'], name='dashboard_s_module_40e44a_idx'), models.Index(fields=['action'], name='dashboard_s_action_849517_idx'), models.Index(fields=['created_at'], name='dashboard_s_created_91a840_idx')],
            },
        ),
    ]
