# Generated by Django 6.0 on 2026-07-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_systemactivitylog'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='doorauditlog',
            name='dashboard_d_created_03c8eb_idx',
        ),
        migrations.RemoveIndex(
            model_name='doorauditlog',
            name='dashboard_d_old_sta_2fb300_idx',
        ),
        migrations.RemoveIndex(
            model_name='doorauditlog',
            name='dashboard_d_new_sta_91a6fd_idx',
        ),
        migrations.DeleteModel(
            name='DoorAuditLog',
        ),
    ]
