# Generated by Django 6.0 on 2026-01-03 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0001_initial'),
        ('distribution', '0002_alter_doorassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='break',
            options={'verbose_name': 'راحة', 'verbose_name_plural': 'الراحات'},
        ),
        migrations.AlterField(
            model_name='break',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.doorassignment', verbose_name='توزيع الموظف'),
        ),
        migrations.AlterField(
            model_name='break',
            name='end_time',
            field=models.TimeField(verbose_name='وقت نهاية الراحة'),
        ),
        migrations.AlterField(
            model_name='break',
            name='start_time',
            field=models.TimeField(verbose_name='وقت بداية الراحة'),
        ),
    ]
