# Generated by Django 6.0 on 2026-06-23 21:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0002_alter_break_options_alter_break_assignment_and_more'),
        ('distribution', '0003_alter_doorassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='break',
            options={'ordering': ['start_time'], 'verbose_name': 'راحة', 'verbose_name_plural': 'الراحات'},
        ),
        migrations.AddField(
            model_name='break',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='break',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='break',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='distribution.doorassignment', verbose_name='توزيع الموظف'),
        ),
    ]
