# Generated by Django 6.0 on 2026-06-23 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0003_alter_break_options_break_created_at_break_notes_and_more'),
        ('hr', '0005_alter_employee_options_and_more'),
        ('scheduling', '0005_alter_shiftassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='break',
            options={'ordering': ['shift_type__name', 'rest_days', 'employee__employee_number'], 'verbose_name': 'راحة', 'verbose_name_plural': 'الراحات'},
        ),
        migrations.RemoveField(
            model_name='break',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='break',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='break',
            name='start_time',
        ),
        migrations.AddField(
            model_name='break',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='weekly_breaks', to='hr.employee', verbose_name='الموظف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='break',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='break',
            name='job_title',
            field=models.CharField(choices=[('shift_head', 'رئيس الوردية'), ('shift_deputy', 'نائب الوردية'), ('supervisor', 'مشرف'), ('monitor', 'مراقب'), ('senior_admin', 'كبير الإداريين'), ('admin', 'إداري'), ('technician', 'فني')], db_index=True, default='friday_saturday', max_length=30, verbose_name='المسمى في الوردية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='break',
            name='rest_days',
            field=models.CharField(choices=[('friday_saturday', 'الجمعة - السبت'), ('saturday_sunday', 'السبت - الأحد'), ('sunday_monday', 'الأحد - الاثنين'), ('monday_tuesday', 'الاثنين - الثلاثاء'), ('tuesday_wednesday', 'الثلاثاء - الأربعاء'), ('wednesday_thursday', 'الأربعاء - الخميس'), ('thursday_friday', 'الخميس - الجمعة')], db_index=True, default=True, max_length=40, verbose_name='أيام الراحة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='break',
            name='shift_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='weekly_breaks', to='scheduling.shifttype', verbose_name='نوع الوردية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='break',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddIndex(
            model_name='break',
            index=models.Index(fields=['employee'], name='breaks_brea_employe_5e9b59_idx'),
        ),
        migrations.AddIndex(
            model_name='break',
            index=models.Index(fields=['shift_type'], name='breaks_brea_shift_t_9611e3_idx'),
        ),
        migrations.AddIndex(
            model_name='break',
            index=models.Index(fields=['job_title'], name='breaks_brea_job_tit_06b918_idx'),
        ),
        migrations.AddIndex(
            model_name='break',
            index=models.Index(fields=['rest_days'], name='breaks_brea_rest_da_47aa6d_idx'),
        ),
        migrations.AddIndex(
            model_name='break',
            index=models.Index(fields=['is_active'], name='breaks_brea_is_acti_8ea746_idx'),
        ),
        migrations.AddConstraint(
            model_name='break',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('employee', 'shift_type'), name='unique_active_break_per_employee_shift'),
        ),
    ]
