# Generated by Django 6.0 on 2026-08-01 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0004_alter_break_options_remove_break_assignment_and_more'),
        ('hr', '0005_alter_employee_options_and_more'),
        ('scheduling', '0008_season_seasonalshifttemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_id_snapshot', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='معرف الراحة المحفوظ')),
                ('action', models.CharField(choices=[('create', 'إنشاء راحة'), ('update', 'تعديل راحة'), ('activate', 'تفعيل راحة'), ('deactivate', 'تعطيل راحة'), ('delete', 'حذف راحة')], db_index=True, max_length=20, verbose_name='الإجراء')),
                ('old_value', models.JSONField(blank=True, default=dict, verbose_name='القيمة السابقة')),
                ('new_value', models.JSONField(blank=True, default=dict, verbose_name='القيمة الجديدة')),
                ('reason', models.TextField(blank=True, verbose_name='سبب الإجراء')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإجراء')),
            ],
            options={
                'verbose_name': 'سجل تغيير راحة',
                'verbose_name_plural': 'سجل تغييرات الراحات',
                'ordering': ['-created_at', '-id'],
                'permissions': [('can_view_break_audit_history', 'يمكن عرض سجل تدقيق الراحات')],
            },
        ),
        migrations.AlterModelOptions(
            name='break',
            options={'ordering': ['shift_type__name', 'rest_days', 'employee__employee_number'], 'permissions': [('can_view_break_dashboard', 'يمكن عرض لوحة الراحات'), ('can_create_employee_break', 'يمكن إضافة راحة موظف'), ('can_update_employee_break', 'يمكن تعديل راحة موظف'), ('can_toggle_employee_break', 'يمكن تفعيل أو تعطيل راحة موظف'), ('can_delete_employee_break', 'يمكن حذف راحة موظف'), ('can_view_break_history', 'يمكن عرض سجل تغييرات الراحات')], 'verbose_name': 'راحة', 'verbose_name_plural': 'الراحات'},
        ),
        migrations.RenameIndex(
            model_name='break',
            new_name='break_employee_idx',
            old_name='breaks_brea_employe_5e9b59_idx',
        ),
        migrations.RenameIndex(
            model_name='break',
            new_name='break_shift_type_idx',
            old_name='breaks_brea_shift_t_9611e3_idx',
        ),
        migrations.RenameIndex(
            model_name='break',
            new_name='break_job_title_idx',
            old_name='breaks_brea_job_tit_06b918_idx',
        ),
        migrations.RenameIndex(
            model_name='break',
            new_name='break_rest_days_idx',
            old_name='breaks_brea_rest_da_47aa6d_idx',
        ),
        migrations.RenameIndex(
            model_name='break',
            new_name='break_active_idx',
            old_name='breaks_brea_is_acti_8ea746_idx',
        ),
        migrations.AlterField(
            model_name='break',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='break',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddIndex(
            model_name='break',
            index=models.Index(fields=['shift_type', 'rest_days', 'is_active'], name='break_shift_days_active_idx'),
        ),
        migrations.AddIndex(
            model_name='break',
            index=models.Index(fields=['employee', 'is_active'], name='break_employee_active_idx'),
        ),
        migrations.AddField(
            model_name='breakhistory',
            name='break_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='breaks.break', verbose_name='سجل الراحة'),
        ),
        migrations.AddField(
            model_name='breakhistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='break_history_entries', to='hr.employee', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='breakhistory',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_break_history_actions', to=settings.AUTH_USER_MODEL, verbose_name='منفذ الإجراء'),
        ),
        migrations.AddField(
            model_name='breakhistory',
            name='shift_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='break_history_entries', to='scheduling.shifttype', verbose_name='نوع الوردية'),
        ),
        migrations.AddIndex(
            model_name='breakhistory',
            index=models.Index(fields=['break_id_snapshot', 'created_at'], name='break_hist_record_date_idx'),
        ),
        migrations.AddIndex(
            model_name='breakhistory',
            index=models.Index(fields=['employee', 'created_at'], name='break_hist_employee_date_idx'),
        ),
        migrations.AddIndex(
            model_name='breakhistory',
            index=models.Index(fields=['shift_type', 'created_at'], name='break_hist_shift_date_idx'),
        ),
        migrations.AddIndex(
            model_name='breakhistory',
            index=models.Index(fields=['action', 'created_at'], name='break_hist_action_date_idx'),
        ),
        migrations.AddIndex(
            model_name='breakhistory',
            index=models.Index(fields=['performed_by', 'created_at'], name='break_hist_user_date_idx'),
        ),
    ]
