# Generated by Django 6.0 on 2026-08-09 04:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='استخدم الصيغة الدولية، مثال: +9665XXXXXXXX.', max_length=16, validators=[django.core.validators.RegexValidator(message='رقم الجوال يجب أن يكون بالصيغة الدولية E.164، مثال: +9665XXXXXXXX.', regex='^\\+[1-9]\\d{7,14}$')], verbose_name='رقم الجوال'),
        ),
    ]
