# Generated by Django 6.0 on 2026-08-09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("accounts", "0003_accountprofile_phone_number")]

    operations = [
        migrations.CreateModel(
            name="TwoFactorAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event", models.CharField(choices=[("2fa_required", "2FA required"), ("2fa_send_started", "OTP send started"), ("2fa_send_succeeded", "OTP send succeeded"), ("2fa_send_failed", "OTP send failed"), ("2fa_verify_started", "OTP verification started"), ("2fa_verify_succeeded", "OTP verification succeeded"), ("2fa_verify_failed", "OTP verification failed"), ("2fa_rate_limited", "Rate limited"), ("2fa_expired", "OTP expired"), ("2fa_replay_blocked", "Replay blocked"), ("2fa_max_attempts_reached", "Maximum attempts reached"), ("2fa_channel_changed", "Channel changed"), ("2fa_resend_requested", "Resend requested"), ("2fa_pending_session_expired", "Pending session expired"), ("2fa_session_completed", "Session completed"), ("2fa_invalid_session", "Invalid pending session")], db_index=True, max_length=40)),
                ("channel", models.CharField(blank=True, db_index=True, max_length=20)),
                ("status", models.CharField(blank=True, db_index=True, max_length=20)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name="two_factor_audit_logs", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(model_name="twofactorauditlog", index=models.Index(fields=["user", "created_at"], name="accounts_tw_user_id_2c69f1_idx")),
        migrations.AddIndex(model_name="twofactorauditlog", index=models.Index(fields=["event", "created_at"], name="accounts_tw_event_0ea24a_idx")),
    ]