# Generated by Django 6.0 on 2026-08-13 06:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_twofactorauditlog'),
        ('hr', '0010_employee_operational_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('employee_number', models.CharField(db_index=True, max_length=20, verbose_name='الرقم الوظيفي')),
                ('requested_username', models.CharField(db_index=True, max_length=150, verbose_name='اسم المستخدم المطلوب')),
                ('email', models.EmailField(db_index=True, max_length=255, verbose_name='البريد الإلكتروني')),
                ('phone_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='رقم الجوال يجب أن يكون بالصيغة الدولية E.164، مثال: +9665XXXXXXXX.', regex='^\\+[1-9]\\d{7,14}$')], verbose_name='رقم الجوال')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], db_index=True, default='male', max_length=10, verbose_name='الجنس')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], db_index=True, default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('review_notes', models.TextField(blank=True, verbose_name='ملاحظات المراجعة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_account_requests', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم الذي تم إنشاؤه')),
                ('linked_employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_registration_request', to='hr.employee', verbose_name='سجل الموظف المرتبط')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_account_registration_requests', to=settings.AUTH_USER_MODEL, verbose_name='راجع الطلب بواسطة')),
            ],
            options={
                'verbose_name': 'طلب إنشاء حساب',
                'verbose_name_plural': 'طلبات إنشاء الحساب',
                'ordering': ['-created_at'],
            },
        ),
    ]
