# Generated by Django 6.0 on 2026-08-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accountregistrationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountregistrationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('needs_edit', 'تحتاج مراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], db_index=True, default='pending', max_length=20, verbose_name='حالة الطلب'),
        ),
    ]
