# Generated by Django 6.0 on 2026-01-03 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
        ('scheduling', '0002_alter_shiftassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'تقرير وردية', 'verbose_name_plural': 'تقارير الورديات'},
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='created_by',
            field=models.CharField(blank=True, max_length=150, verbose_name='أُنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء التقرير'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='shift_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.shiftplan', verbose_name='الوردية'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='summary',
            field=models.TextField(verbose_name='ملخص التقرير'),
        ),
    ]
