# Generated by Django 6.0 on 2026-02-12 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_alter_shiftreport_options_shiftreport_created_by_and_more'),
        ('scheduling', '0005_alter_shiftassignment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftreport',
            options={'ordering': ['-created_at'], 'permissions': [('can_generate_shift_report', 'يمكن إنشاء تقرير وردية'), ('can_approve_shift_report', 'يمكن اعتماد التقرير')], 'verbose_name': 'تقرير وردية', 'verbose_name_plural': 'تقارير الورديات'},
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد'),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_shift_reports', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة'),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='closed_doors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='completed_maintenance_requests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='maintenance_doors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='open_doors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='recommendations',
            field=models.TextField(blank=True, verbose_name='التوصيات'),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='report_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم التقرير'),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='snapshot_data',
            field=models.JSONField(blank=True, null=True, verbose_name='بيانات Snapshot الكاملة'),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('final', 'نهائي'), ('approved', 'معتمد')], db_index=True, default='draft', max_length=20, verbose_name='حالة التقرير'),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='total_doors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='total_employees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shiftreport',
            name='total_maintenance_requests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shift_reports', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='shift_plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='scheduling.shiftplan', verbose_name='الوردية'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='summary',
            field=models.TextField(blank=True, verbose_name='الملخص التنفيذي'),
        ),
    ]
