# Generated by Django 6.0 on 2026-02-13 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_alter_shiftreport_options_shiftreport_approved_at_and_more'),
        ('scheduling', '0005_alter_shiftassignment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftreport',
            options={'ordering': ['-created_at'], 'permissions': [('can_generate_shift_report', 'يمكن إنشاء تقرير وردية'), ('can_approve_shift_report', 'يمكن اعتماد التقرير')]},
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_shift_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shift_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='report_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='shift_plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='scheduling.shiftplan'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='snapshot_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('final', 'نهائي'), ('approved', 'معتمد')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='shiftreport',
            index=models.Index(fields=['status'], name='reporting_s_status_506080_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftreport',
            index=models.Index(fields=['created_at'], name='reporting_s_created_5ef820_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftreport',
            index=models.Index(fields=['shift_plan'], name='reporting_s_shift_p_42345a_idx'),
        ),
        migrations.AddConstraint(
            model_name='shiftreport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approved_at__isnull', False), ('approved_by__isnull', False), ('status', 'approved')), models.Q(('approved_at__isnull', True), ('approved_by__isnull', True), ('status__in', ['draft', 'final'])), _connector='OR'), name='shiftreport_approved_fields_only_when_approved'),
        ),
    ]
