# Generated by Django 6.0 on 2026-07-05 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_alter_shiftreport_options_and_more'),
        ('scheduling', '0006_alter_shiftassignment_options_shiftassignment_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftreport',
            name='report_type',
            field=models.CharField(choices=[('operational', 'تقرير تشغيلي'), ('manual', 'تقرير إداري')], db_index=True, default='operational', max_length=20, verbose_name='نوع التقرير'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='shift_plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='scheduling.shiftplan', verbose_name='الوردية'),
        ),
        migrations.AddIndex(
            model_name='shiftreport',
            index=models.Index(fields=['report_type'], name='reporting_s_report__845938_idx'),
        ),
    ]
