# Generated by Django 6.0 on 2026-08-01 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_shiftreport_report_type_alter_shiftreport_shift_plan_and_more'),
        ('scheduling', '0008_season_seasonalshifttemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftreport',
            options={'ordering': ['-created_at', '-id'], 'permissions': [('can_generate_shift_report', 'يمكن إنشاء تقرير وردية'), ('can_approve_shift_report', 'يمكن اعتماد التقرير')], 'verbose_name': 'تقرير وردية', 'verbose_name_plural': 'تقارير الورديات'},
        ),
        migrations.RenameIndex(
            model_name='shiftreport',
            new_name='report_status_idx',
            old_name='reporting_s_status_506080_idx',
        ),
        migrations.RenameIndex(
            model_name='shiftreport',
            new_name='report_type_idx',
            old_name='reporting_s_report__845938_idx',
        ),
        migrations.RenameIndex(
            model_name='shiftreport',
            new_name='report_created_idx',
            old_name='reporting_s_created_5ef820_idx',
        ),
        migrations.RenameIndex(
            model_name='shiftreport',
            new_name='report_shift_idx',
            old_name='reporting_s_shift_p_42345a_idx',
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_shift_reports', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='closed_doors',
            field=models.PositiveIntegerField(default=0, verbose_name='الأبواب المغلقة'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='completed_maintenance_requests',
            field=models.PositiveIntegerField(default=0, verbose_name='طلبات الصيانة المنجزة'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shift_reports', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='maintenance_doors',
            field=models.PositiveIntegerField(default=0, verbose_name='الأبواب تحت الصيانة'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='open_doors',
            field=models.PositiveIntegerField(default=0, verbose_name='الأبواب المفتوحة'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='recommendations',
            field=models.TextField(blank=True, verbose_name='التوصيات'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='report_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True, verbose_name='رقم التقرير'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='snapshot_data',
            field=models.JSONField(blank=True, null=True, verbose_name='نسخة البيانات التشغيلية'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('final', 'نهائي'), ('approved', 'معتمد')], db_index=True, default='draft', max_length=20, verbose_name='حالة التقرير'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='summary',
            field=models.TextField(blank=True, verbose_name='الملخص'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='total_doors',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي الأبواب'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='total_employees',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي الموظفين'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='total_maintenance_requests',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي طلبات الصيانة'),
        ),
        migrations.AddConstraint(
            model_name='shiftreport',
            constraint=models.CheckConstraint(condition=models.Q(('open_doors__lte', models.F('total_doors'))), name='shiftreport_open_doors_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='shiftreport',
            constraint=models.CheckConstraint(condition=models.Q(('closed_doors__lte', models.F('total_doors'))), name='shiftreport_closed_doors_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='shiftreport',
            constraint=models.CheckConstraint(condition=models.Q(('maintenance_doors__lte', models.F('total_doors'))), name='shiftreport_maintenance_doors_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='shiftreport',
            constraint=models.CheckConstraint(condition=models.Q(('completed_maintenance_requests__lte', models.F('total_maintenance_requests'))), name='shiftreport_completed_maintenance_lte_total'),
        ),
    ]
