# Generated by Django 6.0 on 2026-07-05 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, max_length=100, verbose_name='القسم')),
                ('file_name', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('export_format', models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF'), ('csv', 'CSV')], db_index=True, default='excel', max_length=20)),
                ('records_count', models.PositiveIntegerField(default=0, verbose_name='عدد السجلات')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت التصدير')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'عملية تصدير',
                'verbose_name_plural': 'سجل عمليات التصدير',
                'ordering': ['-created_at'],
            },
        ),
    ]
