# Generated by Django 6.0 on 2026-07-05 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports_center', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportlog',
            name='export_format',
            field=models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF'), ('csv', 'CSV')], db_index=True, default='excel', max_length=20, verbose_name='الصيغة'),
        ),
        migrations.AlterField(
            model_name='exportlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
