# Generated by Django 6.0 on 2026-07-20 06:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports_center', '0002_alter_exportlog_export_format_alter_exportlog_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exportlog',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت اكتمال التصدير'),
        ),
        migrations.AddField(
            model_name='exportlog',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد مرات التنزيل'),
        ),
        migrations.AddField(
            model_name='exportlog',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='تفاصيل الخطأ'),
        ),
        migrations.AddField(
            model_name='exportlog',
            name='file',
            field=models.FileField(blank=True, help_text='نسخة محفوظة من الملف لإعادة تنزيله لاحقًا.', null=True, upload_to='exports/%Y/%m/%d/', verbose_name='الملف المحفوظ'),
        ),
        migrations.AddField(
            model_name='exportlog',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='حجم الملف بالبايت'),
        ),
        migrations.AddField(
            model_name='exportlog',
            name='filters',
            field=models.JSONField(blank=True, default=dict, help_text='يحفظ الفترة والوردية والحالة والخيارات المستخدمة.', verbose_name='فلاتر وخيارات التصدير'),
        ),
        migrations.AddField(
            model_name='exportlog',
            name='last_downloaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر تنزيل'),
        ),
        migrations.AddField(
            model_name='exportlog',
            name='report_key',
            field=models.SlugField(blank=True, help_text='معرّف برمجي ثابت لنوع التقرير.', max_length=100, verbose_name='معرّف التقرير'),
        ),
        migrations.AddField(
            model_name='exportlog',
            name='requested_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP'),
        ),
        migrations.AddField(
            model_name='exportlog',
            name='status',
            field=models.CharField(choices=[('processing', 'قيد المعالجة'), ('success', 'مكتمل'), ('failed', 'فشل')], db_index=True, default='processing', max_length=20, verbose_name='حالة العملية'),
        ),
        migrations.AddField(
            model_name='exportlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='exportlog',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='بيانات المتصفح'),
        ),
        migrations.AlterField(
            model_name='exportlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت بدء التصدير'),
        ),
        migrations.AlterField(
            model_name='exportlog',
            name='export_format',
            field=models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF'), ('csv', 'CSV'), ('word', 'Word')], db_index=True, default='excel', max_length=20, verbose_name='صيغة التصدير'),
        ),
        migrations.AlterField(
            model_name='exportlog',
            name='module',
            field=models.CharField(db_index=True, help_text='اسم القسم أو السجل الذي تم تصديره.', max_length=100, verbose_name='القسم'),
        ),
        migrations.AddIndex(
            model_name='exportlog',
            index=models.Index(fields=['status', 'created_at'], name='export_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='exportlog',
            index=models.Index(fields=['export_format', 'created_at'], name='export_format_date_idx'),
        ),
        migrations.AddIndex(
            model_name='exportlog',
            index=models.Index(fields=['module', 'created_at'], name='export_module_date_idx'),
        ),
        migrations.AddIndex(
            model_name='exportlog',
            index=models.Index(fields=['user', 'created_at'], name='export_user_date_idx'),
        ),
    ]
