# Generated by Django 6.0 on 2026-07-25 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports_center', '0003_exportlog_completed_at_exportlog_download_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exportlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='بيانات إضافية مثل مؤشرات الأداء ومعلومات الوردية والمعاينة.', verbose_name='بيانات إضافية'),
        ),
        migrations.AddField(
            model_name='exportlog',
            name='report_name',
            field=models.CharField(blank=True, help_text='الاسم الظاهر للمستخدم مثل سجل الموظفين.', max_length=255, verbose_name='اسم التقرير'),
        ),
        migrations.AddField(
            model_name='exportlog',
            name='started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='وقت بدء المعالجة'),
        ),
        migrations.AddField(
            model_name='exportlog',
            name='storage_path',
            field=models.CharField(blank=True, help_text='مسار الملف داخل وسيط التخزين.', max_length=1000, verbose_name='مسار الملف'),
        ),
        migrations.AlterField(
            model_name='exportlog',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='وقت اكتمال التصدير'),
        ),
        migrations.AlterField(
            model_name='exportlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت طلب التصدير'),
        ),
        migrations.AlterField(
            model_name='exportlog',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='اسم الملف'),
        ),
        migrations.AlterField(
            model_name='exportlog',
            name='filters',
            field=models.JSONField(blank=True, default=dict, help_text='يحفظ الفترة والوردية والمنطقة والحالات والموظف وبقية خيارات التصدير.', verbose_name='فلاتر وخيارات التصدير'),
        ),
        migrations.AlterField(
            model_name='exportlog',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('success', 'مكتمل'), ('failed', 'فشل')], db_index=True, default='processing', max_length=20, verbose_name='حالة العملية'),
        ),
        migrations.AddIndex(
            model_name='exportlog',
            index=models.Index(fields=['report_key', 'created_at'], name='export_report_date_idx'),
        ),
    ]
