# Generated by Django 6.0 on 2026-07-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_remove_announcement_door_announcement_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='announcements/', verbose_name='المرفق'),
        ),
    ]
