# Generated by Django 6.0 on 2026-08-08 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_announcement_section'),
        ('distribution', '0007_alter_doorassignment_options_and_more'),
        ('hr', '0009_alter_employee_options_employee_gender_and_more'),
        ('locations', '0005_door_operational_section_and_more'),
        ('scheduling', '0008_season_seasonalshifttemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المزود')),
                ('provider_code', models.CharField(max_length=50, unique=True, verbose_name='رمز المزود')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('supports_sms', models.BooleanField(default=False, verbose_name='يدعم SMS')),
                ('supports_whatsapp', models.BooleanField(default=False, verbose_name='يدعم واتساب')),
                ('supports_email', models.BooleanField(default=False, verbose_name='يدعم البريد الإلكتروني')),
                ('base_url', models.URLField(blank=True, verbose_name='الرابط الأساسي')),
                ('sender_name', models.CharField(blank=True, max_length=100, verbose_name='اسم المرسل')),
                ('timeout_seconds', models.PositiveIntegerField(default=15, verbose_name='مهلة الاتصال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مزود اتصالات',
                'verbose_name_plural': 'مزودو الاتصالات',
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم القالب')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='رمز القالب')),
                ('channel', models.CharField(choices=[('sms', 'رسالة نصية'), ('whatsapp', 'واتساب'), ('email', 'بريد إلكتروني')], db_index=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='الموضوع')),
                ('body', models.TextField(verbose_name='النص')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('section', models.CharField(choices=[('all', 'الكل'), ('male', 'رجالي'), ('female', 'نسائي')], db_index=True, default='all', max_length=10, verbose_name='القسم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قالب رسالة',
                'verbose_name_plural': 'قوالب الرسائل',
                'indexes': [models.Index(fields=['channel', 'section', 'is_active'], name='communicati_channel_c510fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'رسالة نصية'), ('whatsapp', 'واتساب'), ('email', 'بريد إلكتروني')], db_index=True, max_length=20)),
                ('section', models.CharField(choices=[('male', 'رجالي'), ('female', 'نسائي'), ('all', 'الكل')], db_index=True, default='all', max_length=10)),
                ('recipient_address', models.CharField(max_length=254, verbose_name='عنوان المستلم')),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message_body', models.TextField()),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد الإرسال'), ('sent', 'أرسلت'), ('delivered', 'تم التسليم'), ('failed', 'فشلت'), ('rejected', 'مرفوضة'), ('simulated', 'محاكاة')], db_index=True, default='pending', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('idempotency_key', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_communication_logs', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('recipient_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_logs', to='hr.employee', verbose_name='الموظف المستلم')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_communication_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المستلم')),
                ('related_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_logs', to='distribution.doorassignment', verbose_name='التكليف المرتبط')),
                ('related_door', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_logs', to='locations.door', verbose_name='الباب المرتبط')),
                ('related_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_logs', to='scheduling.shiftplan', verbose_name='الوردية المرتبطة')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_logs', to='communications.communicationprovider', verbose_name='المزود')),
            ],
            options={
                'verbose_name': 'سجل اتصال',
                'verbose_name_plural': 'سجلات الاتصالات',
                'ordering': ['-created_at'],
                'permissions': [('can_view_communications', 'Can view communications'), ('can_send_sms', 'Can send SMS'), ('can_send_whatsapp', 'Can send WhatsApp'), ('can_send_email', 'Can send email'), ('can_retry_message', 'Can retry message'), ('can_view_communication_errors', 'Can view communication errors'), ('can_manage_message_templates', 'Can manage message templates')],
                'indexes': [models.Index(fields=['status'], name='communicati_status_2ef9bb_idx'), models.Index(fields=['channel'], name='communicati_channel_b6f991_idx'), models.Index(fields=['section'], name='communicati_section_8ba3e5_idx'), models.Index(fields=['created_at'], name='communicati_created_5c9e16_idx'), models.Index(fields=['recipient_employee'], name='communicati_recipie_e3aca1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='unique_communication_idempotency_key')],
            },
        ),
    ]
