# Generated by Django 6.0 on 2026-08-08 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_communicationprovider_messagetemplate_and_more'),
        ('hr', '0009_alter_employee_options_employee_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('channel', models.CharField(choices=[('sms', 'رسالة نصية'), ('whatsapp', 'واتساب'), ('email', 'بريد إلكتروني'), ('voice', 'صوتي')], max_length=20)),
                ('provider_template_id', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قالب OTP',
                'verbose_name_plural': 'قوالب OTP',
            },
        ),
        migrations.AddField(
            model_name='communicationprovider',
            name='supports_face',
            field=models.BooleanField(default=False, verbose_name='يدعم التحقق بالوجه'),
        ),
        migrations.AddField(
            model_name='communicationprovider',
            name='supports_nafath',
            field=models.BooleanField(default=False, verbose_name='يدعم نفاذ'),
        ),
        migrations.AddField(
            model_name='communicationprovider',
            name='supports_voice',
            field=models.BooleanField(default=False, verbose_name='يدعم الصوت'),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='channel',
            field=models.CharField(choices=[('sms', 'رسالة نصية'), ('whatsapp', 'واتساب'), ('email', 'بريد إلكتروني'), ('voice', 'صوتي'), ('face', 'تحقق بالوجه'), ('nafath', 'نفاذ')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد الإرسال'), ('sent', 'أرسلت'), ('delivered', 'تم التسليم'), ('failed', 'فشلت'), ('rejected', 'مرفوضة'), ('simulated', 'محاكاة'), ('verified', 'تم التحقق'), ('expired', 'منتهية')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='channel',
            field=models.CharField(choices=[('sms', 'رسالة نصية'), ('whatsapp', 'واتساب'), ('email', 'بريد إلكتروني'), ('voice', 'صوتي')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='CommunicationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_enabled', models.BooleanField(default=True)),
                ('whatsapp_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('preferred_channel', models.CharField(choices=[('sms', 'رسالة نصية'), ('whatsapp', 'واتساب'), ('email', 'بريد إلكتروني'), ('voice', 'صوتي'), ('face', 'تحقق بالوجه'), ('nafath', 'نفاذ')], default='sms', max_length=20)),
                ('allow_fallback', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_preference', to='hr.employee')),
            ],
            options={
                'verbose_name': 'تفضيل اتصالات',
                'verbose_name_plural': 'تفضيلات الاتصالات',
            },
        ),
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('nafath', 'نفاذ'), ('face', 'تحقق بالوجه')], db_index=True, max_length=20)),
                ('provider_request_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('verified', 'تم التحقق'), ('failed', 'فشلت'), ('rejected', 'مرفوضة'), ('expired', 'منتهية'), ('simulated', 'محاكاة')], db_index=True, default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_verifications', to='hr.employee')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.communicationprovider')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تحقق هوية',
                'verbose_name_plural': 'تحققات الهوية',
                'indexes': [models.Index(fields=['verification_type', 'status', 'requested_at'], name='communicati_verific_f83f31_idx')],
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'رسالة نصية'), ('whatsapp', 'واتساب'), ('email', 'بريد إلكتروني'), ('voice', 'صوتي')], db_index=True, max_length=20)),
                ('recipient_masked', models.CharField(max_length=254)),
                ('provider_request_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('sent', 'أرسلت'), ('verified', 'تم التحقق'), ('failed', 'فشلت'), ('rejected', 'مرفوضة'), ('expired', 'منتهية'), ('simulated', 'محاكاة')], db_index=True, default='pending', max_length=20)),
                ('purpose', models.CharField(choices=[('login', 'تسجيل الدخول'), ('password_reset', 'إعادة تعيين كلمة المرور'), ('phone_verification', 'توثيق الجوال'), ('email_verification', 'توثيق البريد'), ('sensitive_action', 'إجراء حساس')], db_index=True, max_length=30)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otp_verifications', to='hr.employee')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otp_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تحقق OTP',
                'verbose_name_plural': 'تحققات OTP',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'purpose', 'created_at'], name='communicati_status_6811f5_idx')],
            },
        ),
    ]
