# Generated by Django 6.0 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0007_otptemplate_communicationprovider_supports_face_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communicationpreference",
            name="preferred_channel",
            field=models.CharField(
                choices=[
                    ("whatsapp", "واتساب"),
                    ("sms", "رسالة نصية"),
                    ("email", "بريد إلكتروني"),
                ],
                default="sms",
                max_length=20,
            ),
        ),
    ]