# Generated by Django 6.0 on 2026-08-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0008_alter_communicationpreference_preferred_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationlog',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد الإرسال'), ('sent', 'أرسلت'), ('delivered', 'تم التسليم'), ('failed', 'فشلت'), ('rejected', 'مرفوضة'), ('simulated', 'محاكاة'), ('verified', 'تم التحقق'), ('expired', 'منتهية'), ('skipped', 'تم التخطي')], db_index=True, default='pending', max_length=20),
        ),
    ]
