# Generated by Django 6.0 on 2026-08-09 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0009_alter_communicationlog_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationlog',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_communications', 'Can view communications'), ('can_send_sms', 'Can send SMS'), ('can_send_whatsapp', 'Can send WhatsApp'), ('can_send_email', 'Can send email'), ('can_retry_message', 'Can retry message'), ('can_retry_assignment_message', 'Can retry assignment message'), ('can_view_communication_errors', 'Can view communication errors'), ('can_manage_message_templates', 'Can manage message templates')], 'verbose_name': 'سجل اتصال', 'verbose_name_plural': 'سجلات الاتصالات'},
        ),
    ]
