# Generated by Django 6.0 on 2026-01-03 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='door',
            options={'ordering': ['name'], 'verbose_name': 'باب', 'verbose_name_plural': 'الأبواب'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name': 'منطقة', 'verbose_name_plural': 'المناطق'},
        ),
        migrations.AddField(
            model_name='zone',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='door',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='door',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اسم الباب'),
        ),
        migrations.AlterField(
            model_name='door',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.zone', verbose_name='المنطقة'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم المنطقة'),
        ),
    ]
