# Generated by Django 6.0 on 2026-06-23 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_door_options_alter_zone_options_zone_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='door',
            options={'ordering': ['door_number', 'name'], 'verbose_name': 'باب', 'verbose_name_plural': 'الأبواب'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['name'], 'verbose_name': 'منطقة', 'verbose_name_plural': 'المناطق'},
        ),
        migrations.AddField(
            model_name='door',
            name='door_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='رقم الباب'),
        ),
        migrations.AddField(
            model_name='door',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='door',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='door',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doors', to='locations.zone', verbose_name='المنطقة'),
        ),
        migrations.AddIndex(
            model_name='door',
            index=models.Index(fields=['door_number'], name='locations_d_door_nu_3f91a7_idx'),
        ),
        migrations.AddIndex(
            model_name='door',
            index=models.Index(fields=['is_active'], name='locations_d_is_acti_1b39a3_idx'),
        ),
        migrations.AddIndex(
            model_name='door',
            index=models.Index(fields=['zone'], name='locations_d_zone_id_30054c_idx'),
        ),
        migrations.AddConstraint(
            model_name='door',
            constraint=models.UniqueConstraint(condition=models.Q(('door_number__isnull', False)), fields=('door_number',), name='unique_door_number_when_exists'),
        ),
    ]
