# Generated by Django 6.0 on 2026-07-14 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_door_options_alter_zone_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='door',
            options={'ordering': ['door_number'], 'verbose_name': 'باب', 'verbose_name_plural': 'الأبواب'},
        ),
        migrations.RemoveConstraint(
            model_name='door',
            name='unique_door_number_when_exists',
        ),
        migrations.RemoveIndex(
            model_name='door',
            name='locations_d_door_nu_3f91a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='door',
            name='locations_d_is_acti_1b39a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='door',
            name='locations_d_zone_id_30054c_idx',
        ),
        migrations.AlterField(
            model_name='door',
            name='door_number',
            field=models.PositiveSmallIntegerField(db_index=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(41)], verbose_name='رقم الباب'),
        ),
        migrations.AlterField(
            model_name='door',
            name='name',
            field=models.CharField(blank=True, help_text='حقل اختياري، ولا يظهر داخل القائمة المنسدلة.', max_length=50, verbose_name='اسم الباب'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='اسم المنطقة'),
        ),
        migrations.AddIndex(
            model_name='door',
            index=models.Index(fields=['is_active', 'door_number'], name='door_active_number_idx'),
        ),
        migrations.AddIndex(
            model_name='door',
            index=models.Index(fields=['zone', 'door_number'], name='door_zone_number_idx'),
        ),
        migrations.AddConstraint(
            model_name='door',
            constraint=models.CheckConstraint(condition=models.Q(('door_number__gte', 1), ('door_number__lte', 41)), name='door_number_between_1_and_41'),
        ),
    ]
