# Generated by Django 6.0 on 2026-08-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_door_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='operational_section',
            field=models.CharField(choices=[('male', 'رجالي'), ('female', 'نسائي'), ('shared', 'رجالي ونسائي')], db_index=True, default='male', editable=False, help_text='يتم تحديد القسم تلقائيًا حسب رقم الباب والقواعد التشغيلية.', max_length=10, verbose_name='القسم التشغيلي'),
        ),
        migrations.AddIndex(
            model_name='door',
            index=models.Index(fields=['operational_section', 'is_active'], name='door_section_active_idx'),
        ),
        migrations.AddIndex(
            model_name='door',
            index=models.Index(fields=['zone', 'operational_section', 'door_number'], name='door_zone_section_idx'),
        ),
        migrations.AddConstraint(
            model_name='door',
            constraint=models.CheckConstraint(condition=models.Q(('operational_section__in', ['male', 'female', 'shared'])), name='door_valid_operational_section'),
        ),
    ]
