# Generated by Django 6.0 on 2026-08-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_door_operational_section_and_more'),
        ('ops', '0017_backfill_legacy_operational_sections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='door',
            options={'ordering': ['sort_order', 'door_number'], 'verbose_name': 'باب', 'verbose_name_plural': 'الأبواب'},
        ),
        migrations.RemoveConstraint(
            model_name='door',
            name='door_number_between_1_and_41',
        ),
        migrations.AddField(
            model_name='door',
            name='sort_order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, editable=False, verbose_name='ترتيب الباب الرسمي'),
        ),
        migrations.AlterField(
            model_name='door',
            name='door_number',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='رقم الباب'),
        ),
        migrations.AddConstraint(
            model_name='door',
            constraint=models.CheckConstraint(condition=models.Q(('door_number__in', ['1', '2', '3', '4', '5', '6B', '6A', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41'])), name='door_code_in_official_catalog'),
        ),
    ]
