# Generated by Django 6.0 on 2026-01-03 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={
                'ordering': ['employee_number'],
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفون',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='الرقم الوظيفي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='على رأس العمل'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='حساب المستخدم',
            ),
        ),

        # ✅ الإصلاح: إضافة عمود job_title فعليًا للجدول
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(
                max_length=50,
                default='staff',
                verbose_name='المسمى الوظيفي',
            ),
        ),
    ]
