# Generated by Django 6.0 on 2026-01-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(choices=[('gm', 'المدير العام'), ('doors_head', 'رئيس قسم الأبواب'), ('doors_deputy', 'وكيل رئيس قسم الأبواب'), ('senior_admin', 'كبير الإداريين للأبواب'), ('admin_secretary', 'سكرتير إداري'), ('fajr_supervisor', 'مشرف وردية الفجر'), ('duha_supervisor', 'مشرف وردية الضحى'), ('evening_supervisor', 'مشرف وردية مسائية'), ('support_supervisor', 'مشرف وردية مساندة'), ('fajr_deputy', 'نائب مشرف الفجر'), ('duha_deputy', 'نائب مشرف الضحى'), ('evening_deputy', 'نائب مشرف المسائية'), ('tech_secretary', 'سكرتير فني')], default='tech_secretary', max_length=50, verbose_name='المسمى الوظيفي'),
        ),
    ]
