# Generated by Django 6.0 on 2026-06-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_employee_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الجوال'),
        ),
    ]
