# Generated by Django 6.0 on 2026-06-23 08:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employee_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_number'], 'permissions': [('can_view_employee_dashboard', 'يمكن عرض لوحة الموظفين'), ('can_activate_employee', 'يمكن تفعيل الموظف'), ('can_deactivate_employee', 'يمكن تعطيل الموظف')], 'verbose_name': 'موظف', 'verbose_name_plural': 'الموظفون'},
        ),
        migrations.AddField(
            model_name='employee',
            name='can_execute_maintenance',
            field=models.BooleanField(default=False, verbose_name='يمكنه تنفيذ الصيانة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_work_on_doors',
            field=models.BooleanField(default=True, verbose_name='يمكن تسكينه على الأبواب'),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإضافة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ المباشرة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='رقم الهوية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_status',
            field=models.CharField(choices=[('active', 'على رأس العمل'), ('inactive', 'غير نشط'), ('vacation', 'إجازة'), ('suspended', 'موقوف مؤقتًا'), ('transferred', 'منقول')], db_index=True, default='active', max_length=20, verbose_name='حالة الموظف'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='الرقم الوظيفي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='نشط في النظام'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(choices=[('gm', 'المدير العام'), ('doors_head', 'رئيس قسم الأبواب'), ('doors_deputy', 'وكيل رئيس قسم الأبواب'), ('senior_admin', 'كبير الإداريين للأبواب'), ('admin_secretary', 'سكرتير إداري'), ('fajr_supervisor', 'مشرف وردية الفجر'), ('duha_supervisor', 'مشرف وردية الضحى'), ('evening_supervisor', 'مشرف وردية مسائية'), ('support_supervisor', 'مشرف وردية مساندة'), ('fajr_deputy', 'نائب مشرف الفجر'), ('duha_deputy', 'نائب مشرف الضحى'), ('evening_deputy', 'نائب مشرف المسائية'), ('tech_secretary', 'سكرتير فني'), ('technician', 'فني صيانة'), ('monitor', 'مراقب أبواب'), ('security', 'أمن وسلامة')], db_index=True, default='monitor', max_length=50, verbose_name='المسمى الوظيفي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='رقم الجوال يجب أن يحتوي على أرقام فقط ويمكن أن يبدأ بـ +', regex='^\\+?\\d{8,15}$')], verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_number'], name='hr_employee_employe_725225_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['full_name'], name='hr_employee_full_na_bb6b90_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['job_title'], name='hr_employee_job_tit_77d45c_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['work_status'], name='hr_employee_work_st_1b258f_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active'], name='hr_employee_is_acti_8381ca_idx'),
        ),
    ]
