# Generated by Django 6.0 on 2026-08-01 17:53

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_employee_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_number'], 'permissions': [('can_view_employee_dashboard', 'يمكن عرض لوحة الموظفين'), ('can_activate_employee', 'يمكن تفعيل الموظف'), ('can_deactivate_employee', 'يمكن تعطيل الموظف'), ('can_hard_delete_employee', 'يمكن حذف الموظف نهائيًا')], 'verbose_name': 'موظف', 'verbose_name_plural': 'الموظفون'},
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='hr_employee_number_idx',
            old_name='hr_employee_employe_725225_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='hr_employee_name_idx',
            old_name='hr_employee_full_na_bb6b90_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='hr_employee_job_idx',
            old_name='hr_employee_job_tit_77d45c_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='hr_employee_status_idx',
            old_name='hr_employee_work_st_1b258f_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='hr_employee_active_idx',
            old_name='hr_employee_is_acti_8381ca_idx',
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, max_length=10, validators=[django.core.validators.RegexValidator(message='رقم الهوية يجب أن يتكون من 10 أرقام.', regex='^\\d{10}$')], verbose_name='رقم الهوية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='رقم الجوال يجب أن يحتوي على أرقام فقط ويمكن أن يبدأ بعلامة +.', regex='^\\+?\\d{8,15}$')], verbose_name='رقم الجوال'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['national_id'], name='hr_employee_nid_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('national_id', ''), _negated=True), fields=('national_id',), name='unique_non_empty_employee_national_id'),
        ),
    ]
