# Generated by Django 6.0 on 2026-08-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_alter_employee_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(choices=[('chairman_office', 'مكتب معالي: رئيس مجلس الإدارة'), ('ceo_office', 'مكتب الرئيس التنفيذي'), ('deputy_ceo_operations', 'نائب الرئيس التنفيذي للتشغيل للمسجد النبوي الشريف'), ('gm', 'المدير العام'), ('doors_head', 'رئيس قسم الأبواب'), ('doors_deputy', 'وكيل رئيس قسم الأبواب'), ('senior_admin', 'كبير الإداريين للأبواب'), ('admin_secretary', 'سكرتير إداري'), ('fajr_supervisor', 'مشرف وردية الفجر'), ('duha_supervisor', 'مشرف وردية الضحى'), ('evening_supervisor', 'مشرف وردية مسائية'), ('support_supervisor', 'مشرف وردية مساندة'), ('fajr_deputy', 'نائب مشرف الفجر'), ('duha_deputy', 'نائب مشرف الضحى'), ('evening_deputy', 'نائب مشرف المسائية'), ('tech_secretary', 'سكرتير فني'), ('technician', 'فني صيانة'), ('monitor', 'مراقب أبواب'), ('security', 'أمن وسلامة')], db_index=True, default='monitor', max_length=50, verbose_name='المسمى الوظيفي'),
        ),
    ]
