# Generated by Django 6.0 on 2026-08-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_alter_employee_job_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_number'], 'permissions': [('can_view_employee_dashboard', 'يمكن عرض لوحة الموظفين'), ('can_view_male_employees', 'يمكن عرض موظفي القسم الرجالي'), ('can_view_female_employees', 'يمكن عرض موظفات القسم النسائي'), ('can_manage_male_employees', 'يمكن إدارة موظفي القسم الرجالي'), ('can_manage_female_employees', 'يمكن إدارة موظفات القسم النسائي'), ('can_activate_employee', 'يمكن تفعيل الموظف'), ('can_deactivate_employee', 'يمكن تعطيل الموظف'), ('can_hard_delete_employee', 'يمكن حذف الموظف نهائيًا')], 'verbose_name': 'موظف', 'verbose_name_plural': 'الموظفون'},
        ),
        migrations.AddField(
            model_name='employee',
            name='operational_section',
            field=models.CharField(blank=True, choices=[('male', 'رجالي'), ('female', 'نسائي')], db_index=True, max_length=10, null=True, verbose_name='القسم التشغيلي'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['operational_section', 'is_active', 'work_status'], name='hr_emp_section_status_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['operational_section', 'can_work_on_doors', 'is_active'], name='hr_emp_section_door_idx'),
        ),
    ]
