# Generated by Django 6.0 on 2026-08-11

from django.db import migrations


WOMEN_DOORS = {
    12, 13, 14,
    15, 16, 23, 24, 25, 26, 27,
    28, 29, 30,
}


def populate_operational_sections(apps, schema_editor):
    Employee = apps.get_model("hr", "Employee")
    DoorAssignment = apps.get_model("distribution", "DoorAssignment")

    for employee in Employee.objects.all().iterator():
        door_numbers = set(
            DoorAssignment.objects.filter(employee_id=employee.pk)
            .values_list("door__door_number", flat=True)
        )

        if not door_numbers:
            continue

        has_women_door = bool(door_numbers & WOMEN_DOORS)
        has_other_door = bool(door_numbers - WOMEN_DOORS)

        if has_women_door and not has_other_door:
            employee.operational_section = "female"
        elif has_other_door and not has_women_door:
            employee.operational_section = "male"
        else:
            continue

        employee.save(update_fields=["operational_section"])


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0009_alter_employee_options_employee_gender_and_more"),
        ("distribution", "0006_alter_doorassignment_options"),
    ]

    operations = [
        migrations.RunPython(
            populate_operational_sections,
            migrations.RunPython.noop,
        ),
    ]