# Generated by Django 6.0 on 2026-01-03 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        ('locations', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_supervisor', models.BooleanField(default=False)),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.door')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employee')),
                ('shift_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.shiftplan')),
            ],
        ),
    ]
