# Generated by Django 6.0 on 2026-01-03 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
        ('hr', '0002_alter_employee_options_and_more'),
        ('locations', '0002_alter_door_options_alter_zone_options_zone_notes_and_more'),
        ('scheduling', '0002_alter_shiftassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doorassignment',
            options={'verbose_name': 'توزيع باب', 'verbose_name_plural': 'توزيعات الأبواب'},
        ),
        migrations.AlterField(
            model_name='doorassignment',
            name='door',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.door', verbose_name='الباب'),
        ),
        migrations.AlterField(
            model_name='doorassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employee', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='doorassignment',
            name='is_supervisor',
            field=models.BooleanField(default=False, verbose_name='مشرف الباب'),
        ),
        migrations.AlterField(
            model_name='doorassignment',
            name='shift_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.shiftplan', verbose_name='الوردية'),
        ),
        migrations.AlterUniqueTogether(
            name='doorassignment',
            unique_together={('shift_plan', 'door', 'employee')},
        ),
    ]
