# Generated by Django 6.0 on 2026-06-23 08:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_alter_doorassignment_options_and_more'),
        ('hr', '0005_alter_employee_options_and_more'),
        ('locations', '0002_alter_door_options_alter_zone_options_zone_notes_and_more'),
        ('scheduling', '0005_alter_shiftassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doorassignment',
            options={'ordering': ['door__name', '-is_supervisor', 'employee__employee_number'], 'permissions': [('can_assign_door_employee', 'يمكن توزيع موظف على باب'), ('can_assign_door_supervisor', 'يمكن تعيين مشرف باب'), ('can_view_distribution_dashboard', 'يمكن عرض لوحة توزيع الأبواب')], 'verbose_name': 'توزيع باب', 'verbose_name_plural': 'توزيعات الأبواب'},
        ),
        migrations.AlterUniqueTogether(
            name='doorassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doorassignment',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ التوزيع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doorassignment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='توزيع نشط'),
        ),
        migrations.AddField(
            model_name='doorassignment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='doorassignment',
            name='role',
            field=models.CharField(choices=[('supervisor', 'مشرف باب'), ('monitor', 'مراقب باب'), ('support', 'مساند'), ('technician', 'فني صيانة')], db_index=True, default='monitor', max_length=20, verbose_name='الدور على الباب'),
        ),
        migrations.AlterField(
            model_name='doorassignment',
            name='door',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='locations.door', verbose_name='الباب'),
        ),
        migrations.AlterField(
            model_name='doorassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='door_assignments', to='hr.employee', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='doorassignment',
            name='is_supervisor',
            field=models.BooleanField(db_index=True, default=False, verbose_name='مشرف الباب'),
        ),
        migrations.AlterField(
            model_name='doorassignment',
            name='shift_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_assignments', to='scheduling.shiftplan', verbose_name='الوردية'),
        ),
        migrations.AddIndex(
            model_name='doorassignment',
            index=models.Index(fields=['shift_plan'], name='distributio_shift_p_8ea4c7_idx'),
        ),
        migrations.AddIndex(
            model_name='doorassignment',
            index=models.Index(fields=['door'], name='distributio_door_id_22bd33_idx'),
        ),
        migrations.AddIndex(
            model_name='doorassignment',
            index=models.Index(fields=['employee'], name='distributio_employe_815571_idx'),
        ),
        migrations.AddIndex(
            model_name='doorassignment',
            index=models.Index(fields=['role'], name='distributio_role_44c9b9_idx'),
        ),
        migrations.AddIndex(
            model_name='doorassignment',
            index=models.Index(fields=['is_active'], name='distributio_is_acti_72fb59_idx'),
        ),
        migrations.AddConstraint(
            model_name='doorassignment',
            constraint=models.UniqueConstraint(fields=('shift_plan', 'door', 'employee'), name='unique_employee_per_door_in_shift'),
        ),
        migrations.AddConstraint(
            model_name='doorassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('shift_plan', 'employee'), name='unique_active_employee_assignment_per_shift'),
        ),
        migrations.AddConstraint(
            model_name='doorassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_supervisor', True)), fields=('shift_plan', 'door'), name='unique_active_supervisor_per_door_shift'),
        ),
    ]
