# Generated by Django 6.0 on 2026-07-31 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_alter_doorassignment_options_and_more'),
        ('hr', '0005_alter_employee_options_and_more'),
        ('locations', '0004_alter_door_options_and_more'),
        ('scheduling', '0008_season_seasonalshifttemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doorassignment',
            options={'ordering': ['door__name', '-is_supervisor', 'employee__employee_number'], 'permissions': [('can_assign_door_employee', 'يمكن توزيع موظف على باب'), ('can_assign_door_supervisor', 'يمكن تعيين مشرف باب'), ('can_view_distribution_dashboard', 'يمكن عرض لوحة توزيع الأبواب'), ('can_auto_assign_employees', 'يمكن تنفيذ التوزيع التلقائي'), ('can_rebalance_distribution', 'يمكن إعادة توازن التوزيع')], 'verbose_name': 'توزيع باب', 'verbose_name_plural': 'توزيعات الأبواب'},
        ),
        migrations.AddField(
            model_name='doorassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_door_assignments', to=settings.AUTH_USER_MODEL, verbose_name='تم التوزيع بواسطة'),
        ),
        migrations.AddField(
            model_name='doorassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.CreateModel(
            name='AssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'إنشاء توزيع'), ('deactivate', 'إلغاء توزيع'), ('move', 'نقل موظف'), ('auto_assign', 'توزيع تلقائي'), ('rebalance', 'إعادة توازن')], db_index=True, max_length=20, verbose_name='الإجراء')),
                ('old_role', models.CharField(blank=True, choices=[('supervisor', 'مشرف باب'), ('monitor', 'مراقب باب'), ('support', 'مساند'), ('technician', 'فني صيانة')], max_length=20, verbose_name='الدور السابق')),
                ('new_role', models.CharField(blank=True, choices=[('supervisor', 'مشرف باب'), ('monitor', 'مراقب باب'), ('support', 'مساند'), ('technician', 'فني صيانة')], max_length=20, verbose_name='الدور الجديد')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإجراء')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_history_entries', to='distribution.doorassignment', verbose_name='التوزيع')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_assignment_history', to='hr.employee', verbose_name='الموظف')),
                ('new_door', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribution_history_as_new_door', to='locations.door', verbose_name='الباب الجديد')),
                ('old_door', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribution_history_as_old_door', to='locations.door', verbose_name='الباب السابق')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_distribution_history_actions', to=settings.AUTH_USER_MODEL, verbose_name='منفذ الإجراء')),
                ('shift_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_assignment_history', to='scheduling.shiftplan', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'سجل توزيع',
                'verbose_name_plural': 'سجل التوزيعات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shift_plan', 'action'], name='dist_hist_shift_action_idx'), models.Index(fields=['employee', 'created_at'], name='dist_hist_employee_date_idx')],
            },
        ),
    ]
