# Generated by Django 6.0 on 2026-07-31 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_alter_doorassignment_options_and_more'),
        ('hr', '0005_alter_employee_options_and_more'),
        ('locations', '0004_alter_door_options_and_more'),
        ('scheduling', '0008_season_seasonalshifttemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assignmenthistory',
            name='dist_hist_shift_action_idx',
        ),
        migrations.RemoveIndex(
            model_name='assignmenthistory',
            name='dist_hist_employee_date_idx',
        ),
        migrations.RenameIndex(
            model_name='doorassignment',
            new_name='dist_assign_shift_idx',
            old_name='distributio_shift_p_8ea4c7_idx',
        ),
        migrations.RenameIndex(
            model_name='doorassignment',
            new_name='dist_assign_door_idx',
            old_name='distributio_door_id_22bd33_idx',
        ),
        migrations.RenameIndex(
            model_name='doorassignment',
            new_name='dist_assign_employee_idx',
            old_name='distributio_employe_815571_idx',
        ),
        migrations.RenameIndex(
            model_name='doorassignment',
            new_name='dist_assign_role_idx',
            old_name='distributio_role_44c9b9_idx',
        ),
        migrations.RenameIndex(
            model_name='doorassignment',
            new_name='dist_assign_active_idx',
            old_name='distributio_is_acti_72fb59_idx',
        ),
        migrations.AddIndex(
            model_name='doorassignment',
            index=models.Index(fields=['shift_plan', 'door', 'is_active'], name='dist_shift_door_active_idx'),
        ),
        migrations.AddIndex(
            model_name='doorassignment',
            index=models.Index(fields=['shift_plan', 'employee', 'is_active'], name='dist_shift_emp_active_idx'),
        ),
        migrations.DeleteModel(
            name='AssignmentHistory',
        ),
    ]
