# Generated by Django 6.0 on 2026-08-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0005_remove_assignmenthistory_dist_hist_shift_action_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doorassignment',
            options={'ordering': ['door__door_number', '-is_supervisor', 'employee__employee_number'], 'permissions': [('can_assign_door_employee', 'يمكن توزيع موظف على باب'), ('can_assign_door_supervisor', 'يمكن تعيين مشرف باب'), ('can_view_distribution_dashboard', 'يمكن عرض لوحة توزيع الأبواب'), ('can_auto_assign_employees', 'يمكن تنفيذ التوزيع التلقائي'), ('can_rebalance_distribution', 'يمكن إعادة توازن التوزيع')], 'verbose_name': 'توزيع باب', 'verbose_name_plural': 'توزيعات الأبواب'},
        ),
    ]
