# Generated by Django 6.0 on 2026-08-06 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0006_alter_doorassignment_options'),
        ('hr', '0008_alter_employee_job_title'),
        ('locations', '0005_door_operational_section_and_more'),
        ('scheduling', '0008_season_seasonalshifttemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doorassignment',
            options={'ordering': ['door__door_number', 'section', '-is_supervisor', 'employee__employee_number'], 'permissions': [('can_assign_door_employee', 'يمكن توزيع موظف على باب'), ('can_assign_door_supervisor', 'يمكن تعيين مشرف باب'), ('can_assign_male_section', 'يمكن التوزيع على القسم الرجالي'), ('can_assign_female_section', 'يمكن التوزيع على القسم النسائي'), ('can_view_distribution_dashboard', 'يمكن عرض لوحة توزيع الأبواب'), ('can_auto_assign_employees', 'يمكن تنفيذ التوزيع التلقائي'), ('can_rebalance_distribution', 'يمكن إعادة توازن التوزيع')], 'verbose_name': 'توزيع باب', 'verbose_name_plural': 'توزيعات الأبواب'},
        ),
        migrations.RemoveConstraint(
            model_name='doorassignment',
            name='unique_employee_per_door_in_shift',
        ),
        migrations.RemoveConstraint(
            model_name='doorassignment',
            name='unique_active_supervisor_per_door_shift',
        ),
        migrations.RemoveIndex(
            model_name='doorassignment',
            name='dist_shift_door_active_idx',
        ),
        migrations.AddField(
            model_name='doorassignment',
            name='section',
            field=models.CharField(choices=[('male', 'رجالي'), ('female', 'نسائي')], db_index=True, default='male', help_text='حدد هل التسكين تابع للقسم الرجالي أو القسم النسائي.', max_length=10, verbose_name='قسم التسكين'),
        ),
        migrations.AddIndex(
            model_name='doorassignment',
            index=models.Index(fields=['section'], name='dist_assign_section_idx'),
        ),
        migrations.AddIndex(
            model_name='doorassignment',
            index=models.Index(fields=['shift_plan', 'door', 'section', 'is_active'], name='dist_shift_door_sec_idx'),
        ),
        migrations.AddIndex(
            model_name='doorassignment',
            index=models.Index(fields=['shift_plan', 'section', 'is_active'], name='dist_shift_sec_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='doorassignment',
            constraint=models.UniqueConstraint(fields=('shift_plan', 'door', 'employee', 'section'), name='unique_employee_door_shift_section'),
        ),
        migrations.AddConstraint(
            model_name='doorassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_supervisor', True)), fields=('shift_plan', 'door', 'section'), name='unique_active_supervisor_door_shift_section'),
        ),
        migrations.AddConstraint(
            model_name='doorassignment',
            constraint=models.CheckConstraint(condition=models.Q(('section__in', ['male', 'female'])), name='assignment_valid_section'),
        ),
    ]
