# Generated by Django 6.0 on 2026-01-03 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduling.shifttype')),
            ],
            options={
                'unique_together': {('date', 'shift_type')},
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employee')),
                ('shift_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.shiftplan')),
            ],
            options={
                'unique_together': {('shift_plan', 'employee')},
            },
        ),
    ]
