# Generated by Django 6.0 on 2026-01-03 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_employee_options_and_more'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftassignment',
            options={'verbose_name': 'تسكين موظف', 'verbose_name_plural': 'تسكين الموظفين'},
        ),
        migrations.AlterModelOptions(
            name='shiftplan',
            options={'ordering': ['-date'], 'verbose_name': 'خطة وردية', 'verbose_name_plural': 'خطط الورديات'},
        ),
        migrations.AlterModelOptions(
            name='shifttype',
            options={'ordering': ['name'], 'verbose_name': 'نوع وردية', 'verbose_name_plural': 'أنواع الورديات'},
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='تم التأكيد'),
        ),
        migrations.AddField(
            model_name='shiftplan',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت النهاية'),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت البداية'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employee', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='shift_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.shiftplan', verbose_name='الوردية'),
        ),
        migrations.AlterField(
            model_name='shiftplan',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='shiftplan',
            name='shift_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduling.shifttype', verbose_name='نوع الوردية'),
        ),
        migrations.AlterField(
            model_name='shifttype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='اسم الوردية'),
        ),
    ]
