# Generated by Django 6.0 on 2026-01-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_alter_shiftassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftplan',
            options={'verbose_name': 'خطة وردية', 'verbose_name_plural': 'خطط الورديات'},
        ),
        migrations.AlterModelOptions(
            name='shifttype',
            options={'verbose_name': 'نوع وردية', 'verbose_name_plural': 'أنواع الورديات'},
        ),
        migrations.AddField(
            model_name='shiftplan',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='وردية نشطة'),
        ),
    ]
