# Generated by Django 6.0 on 2026-01-11 11:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_alter_shiftplan_options_alter_shifttype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftplan',
            options={'ordering': ['-date'], 'verbose_name': 'خطة وردية', 'verbose_name_plural': 'خطط الورديات'},
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ التسكين'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shiftplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shiftplan',
            name='status',
            field=models.CharField(choices=[('preparation', 'قيد التجهيز'), ('running', 'قيد التشغيل'), ('paused', 'متوقفة مؤقتًا'), ('ended', 'منتهية')], db_index=True, default='preparation', max_length=20, verbose_name='حالة الوردية'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='shift_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scheduling.shiftplan', verbose_name='الوردية'),
        ),
        migrations.AlterField(
            model_name='shiftplan',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='وردية نشطة'),
        ),
    ]
