# Generated by Django 6.0 on 2026-01-12 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_employee_job_title'),
        ('scheduling', '0004_alter_shiftplan_options_shiftassignment_assigned_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftassignment',
            options={'permissions': [('can_assign_employee', 'يمكن تسكين الموظف في وردية'), ('can_confirm_assignment', 'يمكن تأكيد التسكين')], 'verbose_name': 'تسكين موظف', 'verbose_name_plural': 'تسكين الموظفين'},
        ),
        migrations.AlterModelOptions(
            name='shiftplan',
            options={'ordering': ['-date', 'shift_type__id'], 'permissions': [('can_activate_shift', 'يمكن تفعيل الوردية'), ('can_update_shift_status', 'يمكن تغيير حالة الوردية')], 'verbose_name': 'خطة وردية', 'verbose_name_plural': 'خطط الورديات'},
        ),
        migrations.AlterModelOptions(
            name='shifttype',
            options={'ordering': ['id'], 'verbose_name': 'نوع وردية', 'verbose_name_plural': 'أنواع الورديات'},
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_assignments', to='hr.employee', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='shiftplan',
            name='shift_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_plans', to='scheduling.shifttype', verbose_name='نوع الوردية'),
        ),
    ]
