# Generated by Django 6.0 on 2026-06-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_employee_options_and_more'),
        ('scheduling', '0005_alter_shiftassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftassignment',
            options={'ordering': ['shift_plan', 'role', 'employee__employee_number'], 'permissions': [('can_assign_employee', 'يمكن تسكين الموظف في وردية'), ('can_confirm_assignment', 'يمكن تأكيد التسكين')], 'verbose_name': 'تسكين موظف', 'verbose_name_plural': 'تسكين الموظفين'},
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='role',
            field=models.CharField(choices=[('shift_head', 'رئيس الوردية'), ('shift_deputy', 'نائب الوردية'), ('supervisor', 'مشرف'), ('monitor', 'مراقب'), ('technician', 'فني'), ('admin', 'إداري'), ('senior_admin', 'كبير الإداريين'), ('support', 'مساند')], db_index=True, default='monitor', max_length=30, verbose_name='الدور التشغيلي'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='is_confirmed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='تم التأكيد'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['shift_plan'], name='scheduling__shift_p_1c407a_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['employee'], name='scheduling__employe_b6d3cb_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['role'], name='scheduling__role_f875a7_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['is_confirmed'], name='scheduling__is_conf_c569d8_idx'),
        ),
    ]
