# Generated by Django 6.0 on 2026-07-19 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_employee_options_and_more'),
        ('scheduling', '0006_alter_shiftassignment_options_shiftassignment_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalShiftSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الجدولة الموسمية')),
                ('season_type', models.CharField(choices=[('ramadan', 'رمضان'), ('hajj', 'الحج')], db_index=True, max_length=20, verbose_name='نوع الموسم')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية الموسم')),
                ('end_date', models.DateField(verbose_name='تاريخ نهاية الموسم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='جدولة موسمية نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
            ],
            options={
                'verbose_name': 'جدولة ورديات موسمية',
                'verbose_name_plural': 'جدولات الورديات الموسمية',
                'ordering': ['-start_date', '-created_at'],
                'permissions': [('can_create_seasonal_schedule', 'يمكن إنشاء جدولة ورديات موسمية')],
            },
        ),
        migrations.CreateModel(
            name='SeasonalShiftTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='وقت البداية الموسمي')),
                ('end_time', models.TimeField(verbose_name='وقت النهاية الموسمي')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='إنشاء هذه الوردية')),
            ],
            options={
                'verbose_name': 'وقت وردية موسمية',
                'verbose_name_plural': 'أوقات الورديات الموسمية',
                'ordering': ['shift_type__id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='shiftassignment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='shiftplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shiftplan',
            name='end_time_override',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت النهاية الموسمي'),
        ),
        migrations.AddField(
            model_name='shiftplan',
            name='schedule_kind',
            field=models.CharField(choices=[('regular', 'اعتيادية'), ('seasonal', 'موسمية')], db_index=True, default='regular', max_length=20, verbose_name='نوع الجدولة'),
        ),
        migrations.AddField(
            model_name='shiftplan',
            name='start_time_override',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت البداية الموسمي'),
        ),
        migrations.AlterField(
            model_name='shiftplan',
            name='date',
            field=models.DateField(db_index=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='shifttype',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت النهاية الرسمي'),
        ),
        migrations.AlterField(
            model_name='shifttype',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت البداية الرسمي'),
        ),
        migrations.AddConstraint(
            model_name='shiftassignment',
            constraint=models.UniqueConstraint(fields=('shift_plan', 'employee'), name='unique_employee_per_shift_plan'),
        ),
        migrations.AddIndex(
            model_name='seasonalshiftschedule',
            index=models.Index(fields=['season_type'], name='scheduling__season__cf01ff_idx'),
        ),
        migrations.AddIndex(
            model_name='seasonalshiftschedule',
            index=models.Index(fields=['start_date', 'end_date'], name='scheduling__start_d_0d7506_idx'),
        ),
        migrations.AddIndex(
            model_name='seasonalshiftschedule',
            index=models.Index(fields=['is_active'], name='scheduling__is_acti_6dae17_idx'),
        ),
        migrations.AddField(
            model_name='shiftplan',
            name='seasonal_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shift_plans', to='scheduling.seasonalshiftschedule', verbose_name='الجدولة الموسمية'),
        ),
        migrations.AddIndex(
            model_name='shiftplan',
            index=models.Index(fields=['date'], name='scheduling__date_ba164b_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftplan',
            index=models.Index(fields=['status'], name='scheduling__status_510238_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftplan',
            index=models.Index(fields=['is_active'], name='scheduling__is_acti_0bf248_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftplan',
            index=models.Index(fields=['schedule_kind'], name='scheduling__schedul_e12a12_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftplan',
            index=models.Index(fields=['seasonal_schedule'], name='scheduling__seasona_9f5a67_idx'),
        ),
        migrations.AddConstraint(
            model_name='shiftplan',
            constraint=models.UniqueConstraint(fields=('date', 'shift_type', 'schedule_kind'), name='unique_shift_plan_per_date_type_and_kind'),
        ),
        migrations.AddField(
            model_name='seasonalshifttime',
            name='seasonal_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_times', to='scheduling.seasonalshiftschedule', verbose_name='الجدولة الموسمية'),
        ),
        migrations.AddField(
            model_name='seasonalshifttime',
            name='shift_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seasonal_times', to='scheduling.shifttype', verbose_name='نوع الوردية'),
        ),
        migrations.AddIndex(
            model_name='seasonalshifttime',
            index=models.Index(fields=['seasonal_schedule'], name='scheduling__seasona_726f56_idx'),
        ),
        migrations.AddIndex(
            model_name='seasonalshifttime',
            index=models.Index(fields=['shift_type'], name='scheduling__shift_t_47a806_idx'),
        ),
        migrations.AddIndex(
            model_name='seasonalshifttime',
            index=models.Index(fields=['is_enabled'], name='scheduling__is_enab_c4bb9e_idx'),
        ),
        migrations.AddConstraint(
            model_name='seasonalshifttime',
            constraint=models.UniqueConstraint(fields=('seasonal_schedule', 'shift_type'), name='unique_shift_type_per_seasonal_schedule'),
        ),
    ]
