# Generated by Django 6.0 on 2026-07-24 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_seasonalshiftschedule_seasonalshifttime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم الموسم')),
                ('season_type', models.CharField(choices=[('ramadan', 'رمضان'), ('hajj', 'الحج'), ('other', 'موسم آخر')], db_index=True, default='other', max_length=20, verbose_name='نوع الموسم')),
                ('start_date', models.DateField(db_index=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(db_index=True, verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشط'), ('inactive', 'معطل'), ('archived', 'مؤرشف')], db_index=True, default='draft', max_length=20, verbose_name='حالة الموسم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SeasonalShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الوردية الموسمية')),
                ('start_time', models.TimeField(verbose_name='وقت البداية')),
                ('end_time', models.TimeField(verbose_name='وقت النهاية')),
                ('crosses_midnight', models.BooleanField(default=False, help_text='فعّل هذا الخيار إذا كانت الوردية تبدأ في يوم وتنتهي بعد منتصف الليل في اليوم التالي.', verbose_name='تمتد لليوم التالي')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشطة')),
                ('ordering', models.PositiveSmallIntegerField(default=1, verbose_name='الترتيب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'قالب وردية موسمية',
                'verbose_name_plural': 'قوالب الورديات الموسمية',
                'ordering': ['season', 'ordering', 'start_time'],
            },
        ),
        migrations.RemoveIndex(
            model_name='seasonalshifttime',
            name='scheduling__seasona_726f56_idx',
        ),
        migrations.RemoveIndex(
            model_name='seasonalshifttime',
            name='scheduling__shift_t_47a806_idx',
        ),
        migrations.RemoveIndex(
            model_name='seasonalshifttime',
            name='scheduling__is_enab_c4bb9e_idx',
        ),
        migrations.RemoveConstraint(
            model_name='seasonalshifttime',
            name='unique_shift_type_per_seasonal_schedule',
        ),
        migrations.AlterModelOptions(
            name='shiftplan',
            options={'ordering': ['-date', 'start_time', 'shift_type'], 'verbose_name': 'خطة وردية', 'verbose_name_plural': 'خطط الورديات'},
        ),
        migrations.AlterModelOptions(
            name='shifttype',
            options={'ordering': ['ordering', 'name'], 'verbose_name': 'نوع وردية', 'verbose_name_plural': 'أنواع الورديات'},
        ),
        migrations.RemoveConstraint(
            model_name='shiftplan',
            name='unique_shift_plan_per_date_type_and_kind',
        ),
        migrations.RemoveIndex(
            model_name='shiftplan',
            name='scheduling__date_ba164b_idx',
        ),
        migrations.RemoveIndex(
            model_name='shiftplan',
            name='scheduling__status_510238_idx',
        ),
        migrations.RemoveIndex(
            model_name='shiftplan',
            name='scheduling__is_acti_0bf248_idx',
        ),
        migrations.RemoveIndex(
            model_name='shiftplan',
            name='scheduling__schedul_e12a12_idx',
        ),
        migrations.RemoveIndex(
            model_name='shiftplan',
            name='scheduling__seasona_9f5a67_idx',
        ),
        migrations.RenameIndex(
            model_name='seasonalshiftschedule',
            new_name='seasonal_schedule_type_idx',
            old_name='scheduling__season__cf01ff_idx',
        ),
        migrations.RenameIndex(
            model_name='seasonalshiftschedule',
            new_name='seasonal_schedule_dates_idx',
            old_name='scheduling__start_d_0d7506_idx',
        ),
        migrations.RenameIndex(
            model_name='seasonalshiftschedule',
            new_name='seasonal_schedule_active_idx',
            old_name='scheduling__is_acti_6dae17_idx',
        ),
        migrations.RenameIndex(
            model_name='shiftassignment',
            new_name='shift_assignment_plan_idx',
            old_name='scheduling__shift_p_1c407a_idx',
        ),
        migrations.RenameIndex(
            model_name='shiftassignment',
            new_name='shift_assignment_emp_idx',
            old_name='scheduling__employe_b6d3cb_idx',
        ),
        migrations.RenameIndex(
            model_name='shiftassignment',
            new_name='shift_assignment_role_idx',
            old_name='scheduling__role_f875a7_idx',
        ),
        migrations.RenameIndex(
            model_name='shiftassignment',
            new_name='shift_assignment_conf_idx',
            old_name='scheduling__is_conf_c569d8_idx',
        ),
        migrations.AddField(
            model_name='shiftplan',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت التفعيل'),
        ),
        migrations.AddField(
            model_name='shiftplan',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_shift_plans', to=settings.AUTH_USER_MODEL, verbose_name='فُعّلت بواسطة'),
        ),
        migrations.AddField(
            model_name='shiftplan',
            name='category',
            field=models.CharField(choices=[('daily', 'يومية'), ('seasonal', 'موسمية')], db_index=True, default='daily', max_length=20, verbose_name='تصنيف الوردية'),
        ),
        migrations.AddField(
            model_name='shiftplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shift_plans', to=settings.AUTH_USER_MODEL, verbose_name='أنشئت بواسطة'),
        ),
        migrations.AddField(
            model_name='shiftplan',
            name='crosses_midnight',
            field=models.BooleanField(default=False, help_text='فعّل هذا الخيار عندما تبدأ الوردية في يوم وتنتهي بعد منتصف الليل في اليوم التالي.', verbose_name='تمتد لليوم التالي'),
        ),
        migrations.AddField(
            model_name='shiftplan',
            name='end_time',
            field=models.TimeField(blank=True, db_index=True, null=True, verbose_name='وقت النهاية'),
        ),
        migrations.AddField(
            model_name='shiftplan',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الإنهاء'),
        ),
        migrations.AddField(
            model_name='shiftplan',
            name='finished_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_shift_plans', to=settings.AUTH_USER_MODEL, verbose_name='أُنهيت بواسطة'),
        ),
        migrations.AddField(
            model_name='shiftplan',
            name='is_finished',
            field=models.BooleanField(db_index=True, default=False, verbose_name='الوردية منتهية'),
        ),
        migrations.AddField(
            model_name='shiftplan',
            name='start_time',
            field=models.TimeField(blank=True, db_index=True, null=True, verbose_name='وقت البداية'),
        ),
        migrations.AddField(
            model_name='shiftplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='نشطة'),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='seasonalshiftschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='seasonalshiftschedule',
            name='end_date',
            field=models.DateField(db_index=True, verbose_name='تاريخ نهاية الموسم'),
        ),
        migrations.AlterField(
            model_name='seasonalshiftschedule',
            name='start_date',
            field=models.DateField(db_index=True, verbose_name='تاريخ بداية الموسم'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ التسكين'),
        ),
        migrations.AlterField(
            model_name='shiftplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='shiftplan',
            name='date',
            field=models.DateField(db_index=True, verbose_name='تاريخ الوردية'),
        ),
        migrations.AlterField(
            model_name='shiftplan',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='الوردية نشطة'),
        ),
        migrations.AlterField(
            model_name='shifttype',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت النهاية الافتراضي'),
        ),
        migrations.AlterField(
            model_name='shifttype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='اسم الوردية'),
        ),
        migrations.AlterField(
            model_name='shifttype',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت البداية الافتراضي'),
        ),
        migrations.AddConstraint(
            model_name='seasonalshiftschedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='seasonal_schedule_end_after_start'),
        ),
        migrations.AddField(
            model_name='season',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_seasons', to=settings.AUTH_USER_MODEL, verbose_name='فُعّل بواسطة'),
        ),
        migrations.AddField(
            model_name='season',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_seasons', to=settings.AUTH_USER_MODEL, verbose_name='أُرشف بواسطة'),
        ),
        migrations.AddField(
            model_name='season',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_seasons', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='shiftplan',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shift_plans', to='scheduling.season', verbose_name='الموسم'),
        ),
        migrations.AddField(
            model_name='seasonalshifttemplate',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to='scheduling.season', verbose_name='الموسم'),
        ),
        migrations.AddField(
            model_name='shiftplan',
            name='seasonal_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_shift_plans', to='scheduling.seasonalshifttemplate', verbose_name='قالب الوردية الموسمية'),
        ),
        migrations.AddIndex(
            model_name='shiftplan',
            index=models.Index(fields=['date', 'is_active'], name='shift_date_active_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftplan',
            index=models.Index(fields=['season', 'date'], name='shift_season_date_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftplan',
            index=models.Index(fields=['category', 'date'], name='shift_category_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='shiftplan',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', True), ('is_finished', True), _negated=True), name='shift_not_active_and_finished'),
        ),
        migrations.AddConstraint(
            model_name='shiftplan',
            constraint=models.UniqueConstraint(fields=('date', 'shift_type', 'season', 'seasonal_template'), name='unique_shift_plan_definition'),
        ),
        migrations.RemoveField(
            model_name='seasonalshifttime',
            name='seasonal_schedule',
        ),
        migrations.RemoveField(
            model_name='seasonalshifttime',
            name='shift_type',
        ),
        migrations.RemoveField(
            model_name='shiftplan',
            name='end_time_override',
        ),
        migrations.RemoveField(
            model_name='shiftplan',
            name='schedule_kind',
        ),
        migrations.RemoveField(
            model_name='shiftplan',
            name='seasonal_schedule',
        ),
        migrations.RemoveField(
            model_name='shiftplan',
            name='start_time_override',
        ),
        migrations.RemoveField(
            model_name='shiftplan',
            name='status',
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='season_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='seasonalshifttemplate',
            index=models.Index(fields=['season', 'is_active'], name='season_template_active_idx'),
        ),
        migrations.AddIndex(
            model_name='seasonalshifttemplate',
            index=models.Index(fields=['season', 'ordering'], name='season_template_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='seasonalshifttemplate',
            constraint=models.UniqueConstraint(fields=('season', 'name'), name='unique_shift_template_name_per_season'),
        ),
        migrations.AddConstraint(
            model_name='seasonalshifttemplate',
            constraint=models.UniqueConstraint(fields=('season', 'start_time', 'end_time'), name='unique_shift_template_time_per_season'),
        ),
        migrations.DeleteModel(
            name='SeasonalShiftTime',
        ),
    ]
