# Generated by Django 6.0.8 on 2026-08-25 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_normalize_employee_operational_sections_for_text_door_codes'),
        ('scheduling', '0008_season_seasonalshifttemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftOperationalLeadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility', models.CharField(choices=[('incident_supervisor', 'مشرف البلاغات'), ('operations_supervisor', 'مشرف العمليات'), ('maintenance_shift_supervisor', 'مشرف الصيانة')], db_index=True, max_length=40, verbose_name='المسؤولية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shift_operational_leadership', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_operational_leadership', to='hr.employee', verbose_name='المسؤول')),
                ('shift_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_leadership', to='scheduling.shiftplan', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'قيادة تشغيلية للوردية',
                'verbose_name_plural': 'القيادة التشغيلية للورديات',
                'ordering': ('shift_plan', 'responsibility'),
                'constraints': [models.UniqueConstraint(fields=('shift_plan', 'responsibility'), name='unique_shift_operational_responsibility')],
            },
        ),
    ]
