"""تعريفات التقارير المفصّلة لمركز التصدير."""

from .employees import (
    EMPLOYEES_COLUMNS_DEFINITION,
    EMPLOYEES_FILTERS_DEFINITION,
)
from .doors import (
    DOORS_COLUMNS_DEFINITION,
    DOORS_FILTERS_DEFINITION,
)
from .incidents import (
    INCIDENTS_COLUMNS_DEFINITION,
    INCIDENTS_FILTERS_DEFINITION,
)
from .reports import (
    REPORTS_COLUMNS_DEFINITION,
    REPORTS_FILTERS_DEFINITION,
)
from .maintenance import (
    MAINTENANCE_COLUMNS_DEFINITION,
    MAINTENANCE_FILTERS_DEFINITION,
)

__all__ = [
    "EMPLOYEES_COLUMNS_DEFINITION",
    "EMPLOYEES_FILTERS_DEFINITION",
    "DOORS_COLUMNS_DEFINITION",
    "DOORS_FILTERS_DEFINITION",
    "INCIDENTS_COLUMNS_DEFINITION",
    "INCIDENTS_FILTERS_DEFINITION",
    "REPORTS_COLUMNS_DEFINITION",
    "REPORTS_FILTERS_DEFINITION",
    "MAINTENANCE_COLUMNS_DEFINITION",
    "MAINTENANCE_FILTERS_DEFINITION",
]
