# Generated by Django 6.0 on 2026-07-29 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution', '0003_alter_doorassignment_options_and_more'),
        ('hr', '0005_alter_employee_options_and_more'),
        ('locations', '0004_alter_door_options_and_more'),
        ('ops', '0014_alter_incident_options_and_more'),
        ('reporting', '0005_shiftreport_report_type_alter_shiftreport_shift_plan_and_more'),
        ('scheduling', '0008_season_seasonalshifttemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.JSONField(blank=True, default=dict, verbose_name='القيمة السابقة')),
                ('new_value', models.JSONField(blank=True, default=dict, verbose_name='القيمة الجديدة')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ التغيير')),
                ('change_reason', models.TextField(blank=True, verbose_name='سبب التغيير')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='distribution.doorassignment', verbose_name='التوزيع')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_changed', to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
                ('door', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_history', to='locations.door', verbose_name='الباب')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_history', to='hr.employee', verbose_name='الموظف')),
                ('shift_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_history', to='scheduling.shiftplan', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'سجل توزيع',
                'verbose_name_plural': 'سجل التوزيعات',
                'ordering': ['-changed_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoorStateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.JSONField(blank=True, default=dict, verbose_name='القيمة السابقة')),
                ('new_value', models.JSONField(blank=True, default=dict, verbose_name='القيمة الجديدة')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ التغيير')),
                ('change_reason', models.TextField(blank=True, verbose_name='سبب التغيير')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_changed', to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
                ('door_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='ops.doorshift', verbose_name='حالة الباب')),
            ],
            options={
                'verbose_name': 'سجل حالة باب',
                'verbose_name_plural': 'سجل حالات الأبواب',
                'ordering': ['-changed_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.JSONField(blank=True, default=dict, verbose_name='القيمة السابقة')),
                ('new_value', models.JSONField(blank=True, default=dict, verbose_name='القيمة الجديدة')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ التغيير')),
                ('change_reason', models.TextField(blank=True, verbose_name='سبب التغيير')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_changed', to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='ops.incident', verbose_name='البلاغ')),
            ],
            options={
                'verbose_name': 'سجل البلاغ',
                'verbose_name_plural': 'سجل البلاغات',
                'ordering': ['-changed_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.JSONField(blank=True, default=dict, verbose_name='القيمة السابقة')),
                ('new_value', models.JSONField(blank=True, default=dict, verbose_name='القيمة الجديدة')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ التغيير')),
                ('change_reason', models.TextField(blank=True, verbose_name='سبب التغيير')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_changed', to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
                ('maintenance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='ops.maintenancerequest', verbose_name='طلب الصيانة')),
            ],
            options={
                'verbose_name': 'سجل حالة الصيانة',
                'verbose_name_plural': 'سجل حالات الصيانة',
                'ordering': ['-changed_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.JSONField(blank=True, default=dict, verbose_name='القيمة السابقة')),
                ('new_value', models.JSONField(blank=True, default=dict, verbose_name='القيمة الجديدة')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ التغيير')),
                ('change_reason', models.TextField(blank=True, verbose_name='سبب التغيير')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('action', models.CharField(choices=[('submitted', 'رفع للاعتماد'), ('approved', 'اعتماد'), ('rejected', 'رفض'), ('returned', 'إعادة للمراجعة'), ('revoked', 'سحب الاعتماد')], max_length=30, verbose_name='الإجراء')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_changed', to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='reporting.shiftreport', verbose_name='التقرير')),
            ],
            options={
                'verbose_name': 'سجل اعتماد التقرير',
                'verbose_name_plural': 'سجل اعتماد التقارير',
                'ordering': ['-changed_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShiftPlanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.JSONField(blank=True, default=dict, verbose_name='القيمة السابقة')),
                ('new_value', models.JSONField(blank=True, default=dict, verbose_name='القيمة الجديدة')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ التغيير')),
                ('change_reason', models.TextField(blank=True, verbose_name='سبب التغيير')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('action', models.CharField(choices=[('created', 'إنشاء'), ('activated', 'تفعيل'), ('updated', 'تعديل'), ('finished', 'إنهاء'), ('cancelled', 'إلغاء'), ('reopened', 'إعادة فتح')], max_length=30, verbose_name='الإجراء')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_changed', to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
                ('shift_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='scheduling.shiftplan', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'سجل الوردية',
                'verbose_name_plural': 'سجل الورديات',
                'ordering': ['-changed_at'],
                'abstract': False,
            },
        ),
    ]
