# Generated by Django 6.0 on 2026-07-31 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('distribution', '0004_alter_doorassignment_options_and_more'),
        ('hr', '0005_alter_employee_options_and_more'),
        ('locations', '0004_alter_door_options_and_more'),
        ('ops', '0015_doorcurrentstate'),
        ('reporting', '0005_shiftreport_report_type_alter_shiftreport_shift_plan_and_more'),
        ('scheduling', '0008_season_seasonalshifttemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmenthistory',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_history_entries', to='distribution.doorassignment', verbose_name='التوزيع'),
        ),
        migrations.AlterField(
            model_name='assignmenthistory',
            name='door',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_assignment_history', to='locations.door', verbose_name='الباب'),
        ),
        migrations.AlterField(
            model_name='assignmenthistory',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_assignment_history', to='hr.employee', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='assignmenthistory',
            name='shift_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_assignment_history', to='scheduling.shiftplan', verbose_name='الوردية'),
        ),
        migrations.AlterField(
            model_name='doorstatehistory',
            name='door_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_state_history', to='ops.doorshift', verbose_name='حالة الباب'),
        ),
        migrations.AlterField(
            model_name='incidentstatushistory',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_status_history', to='ops.incident', verbose_name='البلاغ'),
        ),
        migrations.AlterField(
            model_name='maintenancestatushistory',
            name='maintenance_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_status_history', to='ops.maintenancerequest', verbose_name='طلب الصيانة'),
        ),
        migrations.AlterField(
            model_name='reportapprovalhistory',
            name='action',
            field=models.CharField(choices=[('submitted', 'رفع للاعتماد'), ('approved', 'اعتماد'), ('rejected', 'رفض'), ('returned', 'إعادة للمراجعة'), ('revoked', 'سحب الاعتماد')], db_index=True, max_length=30, verbose_name='الإجراء'),
        ),
        migrations.AlterField(
            model_name='reportapprovalhistory',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_approval_history', to='reporting.shiftreport', verbose_name='التقرير'),
        ),
        migrations.AlterField(
            model_name='shiftplanhistory',
            name='action',
            field=models.CharField(choices=[('created', 'إنشاء'), ('activated', 'تفعيل'), ('updated', 'تعديل'), ('finished', 'إنهاء'), ('cancelled', 'إلغاء'), ('reopened', 'إعادة فتح')], db_index=True, max_length=30, verbose_name='الإجراء'),
        ),
        migrations.AlterField(
            model_name='shiftplanhistory',
            name='shift_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_history_entries', to='scheduling.shiftplan', verbose_name='الوردية'),
        ),
        migrations.AddIndex(
            model_name='assignmenthistory',
            index=models.Index(fields=['assignment', 'changed_at'], name='audit_assign_date_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmenthistory',
            index=models.Index(fields=['employee', 'changed_at'], name='audit_assign_emp_date_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmenthistory',
            index=models.Index(fields=['door', 'changed_at'], name='audit_assign_door_date_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmenthistory',
            index=models.Index(fields=['shift_plan', 'changed_at'], name='audit_assign_shift_date_idx'),
        ),
        migrations.AddIndex(
            model_name='doorstatehistory',
            index=models.Index(fields=['door_shift', 'changed_at'], name='audit_door_state_date_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentstatushistory',
            index=models.Index(fields=['incident', 'changed_at'], name='audit_inc_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancestatushistory',
            index=models.Index(fields=['maintenance_request', 'changed_at'], name='audit_maint_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='reportapprovalhistory',
            index=models.Index(fields=['report', 'action', 'changed_at'], name='audit_report_action_date_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftplanhistory',
            index=models.Index(fields=['shift_plan', 'action', 'changed_at'], name='audit_shift_action_date_idx'),
        ),
    ]
