# Generated by Django 6.0 on 2026-07-25 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='رمز الدور')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم الدور')),
                ('description', models.TextField(blank=True, verbose_name='وصف الدور')),
                ('is_system_role', models.BooleanField(db_index=True, default=False, verbose_name='دور نظامي')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='platform_role', to='auth.group', verbose_name='مجموعة الصلاحيات')),
            ],
            options={
                'verbose_name': 'دور',
                'verbose_name_plural': 'الأدوار والصلاحيات',
                'ordering': ['name'],
                'permissions': [('view_employees', 'يمكن عرض الموظفين'), ('create_employee', 'يمكن إضافة موظف'), ('update_employee', 'يمكن تعديل موظف'), ('disable_employee', 'يمكن تعطيل موظف'), ('view_shifts', 'يمكن عرض الورديات'), ('create_shift', 'يمكن إنشاء وردية'), ('activate_shift', 'يمكن تفعيل وردية'), ('finish_shift', 'يمكن إنهاء وردية'), ('view_distribution', 'يمكن عرض التوزيع'), ('assign_employees', 'يمكن توزيع الموظفين'), ('approve_distribution', 'يمكن اعتماد التوزيع'), ('view_doors', 'يمكن عرض الأبواب'), ('open_door', 'يمكن فتح الباب'), ('close_door', 'يمكن إغلاق الباب'), ('move_door_to_maintenance', 'يمكن تحويل الباب إلى الصيانة'), ('view_maintenance_requests', 'يمكن عرض طلبات الصيانة'), ('create_maintenance_request', 'يمكن إنشاء بلاغ صيانة'), ('approve_maintenance_request', 'يمكن اعتماد طلب صيانة'), ('assign_maintenance_technician', 'يمكن تعيين فني صيانة'), ('close_maintenance_request', 'يمكن إغلاق طلب صيانة'), ('view_reports', 'يمكن عرض التقارير'), ('create_report', 'يمكن إنشاء تقرير'), ('update_report', 'يمكن تعديل تقرير'), ('approve_report', 'يمكن اعتماد تقرير'), ('export_report', 'يمكن تصدير تقرير'), ('view_system_logs', 'يمكن عرض سجلات النظام'), ('manage_users', 'يمكن إدارة المستخدمين'), ('manage_backups', 'يمكن إدارة النسخ الاحتياطية'), ('manage_roles', 'يمكن إدارة الأدوار والصلاحيات')],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإسناد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_platform_roles', to=settings.AUTH_USER_MODEL, verbose_name='أُسند بواسطة')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_assignments', to='roles.role', verbose_name='الدور')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_role_assignments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'دور مستخدم',
                'verbose_name_plural': 'أدوار المستخدمين',
                'ordering': ['user', 'role'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='user_role_active_idx'), models.Index(fields=['role', 'is_active'], name='role_user_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'role'), name='unique_platform_user_role')],
            },
        ),
    ]
