# Generated by Django 6.0.8 on 2026-08-25 16:34

from django.db import migrations


ROLE_DEFINITIONS = {
    "incident_supervisor": ("مشرف البلاغات", [
        "view_shifts", "view_doors", "create_incident", "update_incident",
        "escalate_incident", "convert_incident_to_maintenance", "close_incident",
        "view_maintenance_requests", "view_door_coverage_settings",
        "change_door_coverage_settings",
    ]),
    "operations_supervisor": ("مشرف العمليات", [
        "view_shifts", "view_doors", "view_maintenance_requests",
        "approve_maintenance_request",
    ]),
    "maintenance_shift_supervisor": ("مشرف الصيانة", [
        "view_shifts", "view_doors", "view_maintenance_requests",
        "assign_maintenance_technician", "close_maintenance_request",
    ]),
}


def create_specialist_roles(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")
    Role = apps.get_model("roles", "Role")
    content_type, _ = ContentType.objects.get_or_create(app_label="roles", model="role")
    coverage_permissions = {
        "view_door_coverage_settings": "يمكن عرض إعدادات تغطية الأبواب",
        "change_door_coverage_settings": "يمكن تعديل إعدادات تغطية الأبواب",
    }
    for codename, name in coverage_permissions.items():
        Permission.objects.get_or_create(
            content_type=content_type, codename=codename, defaults={"name": name}
        )
    for code, (name, codenames) in ROLE_DEFINITIONS.items():
        group, _ = Group.objects.get_or_create(name=name)
        role, _ = Role.objects.update_or_create(
            code=code,
            defaults={
                "name": name, "description": "دور تخصصي مرتبط بتكليف الوردية.",
                "group": group, "is_system_role": True, "is_active": True,
                "operational_section": "all",
            },
        )
        permissions = Permission.objects.filter(
            content_type=content_type, codename__in=codenames
        )
        group.permissions.set(permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_alter_role_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'permissions': [('view_employees', 'يمكن عرض الموظفين'), ('create_employee', 'يمكن إضافة موظف'), ('update_employee', 'يمكن تعديل موظف'), ('disable_employee', 'يمكن تعطيل موظف'), ('view_shifts', 'يمكن عرض الورديات'), ('create_shift', 'يمكن إنشاء وردية'), ('activate_shift', 'يمكن تفعيل وردية'), ('finish_shift', 'يمكن إنهاء وردية'), ('view_distribution', 'يمكن عرض التوزيع'), ('assign_employees', 'يمكن توزيع الموظفين'), ('approve_distribution', 'يمكن اعتماد التوزيع'), ('view_doors', 'يمكن عرض الأبواب'), ('open_door', 'يمكن فتح الباب'), ('close_door', 'يمكن إغلاق الباب'), ('move_door_to_maintenance', 'يمكن تحويل الباب إلى الصيانة'), ('view_maintenance_requests', 'يمكن عرض طلبات الصيانة'), ('create_maintenance_request', 'يمكن إنشاء بلاغ صيانة'), ('approve_maintenance_request', 'يمكن اعتماد طلب صيانة'), ('assign_maintenance_technician', 'يمكن تعيين فني صيانة'), ('close_maintenance_request', 'يمكن إغلاق طلب صيانة'), ('create_incident', 'يمكن إنشاء بلاغ تشغيلي'), ('update_incident', 'يمكن تحديث بلاغ تشغيلي'), ('assign_incident', 'يمكن تعيين مسؤول البلاغ'), ('escalate_incident', 'يمكن تصعيد البلاغ'), ('convert_incident_to_maintenance', 'يمكن تحويل البلاغ إلى الصيانة'), ('close_incident', 'يمكن إغلاق البلاغ التشغيلي'), ('view_door_coverage_settings', 'يمكن عرض إعدادات تغطية الأبواب'), ('change_door_coverage_settings', 'يمكن تعديل إعدادات تغطية الأبواب'), ('view_reports', 'يمكن عرض التقارير'), ('create_report', 'يمكن إنشاء تقرير'), ('update_report', 'يمكن تعديل تقرير'), ('approve_report', 'يمكن اعتماد تقرير'), ('export_report', 'يمكن تصدير تقرير'), ('view_system_logs', 'يمكن عرض سجلات النظام'), ('manage_users', 'يمكن إدارة المستخدمين'), ('manage_backups', 'يمكن إدارة النسخ الاحتياطية'), ('manage_roles', 'يمكن إدارة الأدوار والصلاحيات')], 'verbose_name': 'دور', 'verbose_name_plural': 'الأدوار والصلاحيات'},
        ),
        migrations.RunPython(create_specialist_roles, migrations.RunPython.noop),
    ]
