# Generated by Django 6.0 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="section",
            field=models.CharField(
                choices=[
                    ("male", "رجالي"),
                    ("female", "نسائي"),
                    ("all", "الكل"),
                ],
                db_index=True,
                default="all",
                max_length=10,
                verbose_name="القسم التشغيلي",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["section"], name="notificatio_section_97ca07_idx"),
        ),
    ]